repoServer:
  env:
    - name: HELM_REGISTRY_CONFIG
      value: /home/argocd/helm/config.json
  volumeMounts:
    - name: oci-ghcr-helm-auth
      mountPath: /home/argocd/helm
  volumes:
    - name: oci-ghcr-helm-auth
      secret:
        secretName: oci-ghcr-helm-auth
