configs:
  cm:
    oidc.config: |
      name: PocketID
      issuer: https://auth.schaermu.ch
      clientID: ${OIDC_CLIENT_ID}
      clientSecret: ${OIDC_CLIENT_SECRET}

extraEnv:
  - name: OIDC_CLIENT_ID
    valueFrom:
      secretKeyRef:
        name: argocd-oidc-pocketid
        key: OIDC_CLIENT_ID
  - name: OIDC_CLIENT_SECRET
    valueFrom:
      secretKeyRef:
        name: argocd-oidc-pocketid
        key: OIDC_CLIENT_SECRET
