defaultSettings:
  storageReservedPercentageForDefaultDisk: 1
  defaultDataPath: /var/lib/longhorn
  backupTarget: s3://schaermu-k8s-backups@auto/longhorn
  backupTargetCredentialSecret: longhorn-r2-backups
