global:
  nodeSelector:
    schaermu.lab/has-storage: "true"
preUpgradeChecker:
  jobEnabled: false
persistence:
  defaultClassReplicaCount: 2
defaultBackupStore:
  backupTarget: s3://schaermu-k8s-backups@auto/longhorn
  backupTargetCredentialSecret: longhorn-r2-backups
defaultSettings:
  createDefaultDiskLabeledNodes: true
  storageReservedPercentageForDefaultDisk: 1
  defaultDataPath: /var/mnt/longhorn
  orphanAutoDeletion: false
  autoDeletePodWhenVolumeDetachedUnexpectedly: true
  nodeDownPodDeletionPolicy: delete-both-statefulset-and-deployment-pod
  nodeDrainPolicy: always-allow
