---
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: minio-store
  namespace: prowlarr
spec:
  retentionPolicy: 10d
  configuration:
    destinationPath: s3://k8s-homelab-backups/cloudnative-pg
    endpointURL: http://192.168.1.244:9000
    s3Credentials:
      accessKeyId:
        name: prowlarr-minio-store
        key: accessKeyId
      secretAccessKey:
        name: prowlarr-minio-store
        key: secretAccessKey
    wal:
      compression: gzip
    data:
      compression: gzip
  instanceSidecarConfiguration:
    env:
    - name: AWS_REQUEST_CHECKSUM_CALCULATION
      value: when_required
    - name: AWS_RESPONSE_CHECKSUM_VALIDATION
      value: when_required
    retentionPolicyIntervalSeconds: 1800
