---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mediamanager-config
  namespace: mediamanager
data:
  PROWLARR__POSTGRES__HOST: "prowlarr-db.prowlarr.svc.cluster.local"
  PROWLARR__POSTGRES__PORT: "5432"
  PROWLARR__UPDATE__AUTOMATICALLY: "false"
  PROWLARR__UPDATE__MECHANISM: "External"
