---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prowlarr-config
  namespace: prowlarr
data:
  PROWLARR__POSTGRES__HOST: "prowlarr-db.prowlarr.svc.cluster.local"
  PROWLARR__POSTGRES__PORT: "5432"
  PROWLARR__UPDATE__AUTOMATICALLY: "false"
  PROWLARR__UPDATE__MECHANISM: "External"
  PROWLARR__LOG__SQL: "false"
