
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prowlarr-default-config
  namespace: prowlarr
data:
  config.xml: |
    <Config>
      <BindAddress>*</BindAddress>
      <Port>9696</Port>
      <SslPort>6969</SslPort>
      <EnableSsl>False</EnableSsl>
      <LaunchBrowser>False</LaunchBrowser>
      <AuthenticationMethod>Forms</AuthenticationMethod>
      <AuthenticationRequired>DisabledForLocalAddresses</AuthenticationRequired>
      <Branch>master</Branch>
      <LogLevel>info</LogLevel>
      <LogSql>False</LogSql>
      <LogDbEnabled>False</LogDbEnabled>
      <SslCertPath></SslCertPath>
      <SslCertPassword></SslCertPassword>
      <UrlBase>https://prowlarr.lab.schaermu.ch</UrlBase>
      <InstanceName>Prowlarr</InstanceName>
      <UpdateAutomatically>False</UpdateAutomatically>
      <UpdateMechanism>External</UpdateMechanism>
    </Config>
