---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
  namespace: prowlarr
  labels:
    app.kubernetes.io/name: prowlarr
    app.kubernetes.io/instance: prowlarr
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: prowlarr
      app.kubernetes.io/instance: prowlarr
  template:
    metadata:
      labels:
        app.kubernetes.io/name: prowlarr
        app.kubernetes.io/instance: prowlarr
    spec:
      serviceAccountName: prowlarr
      securityContext:
        runAsUser: 3001
        runAsGroup: 3001
        fsGroup: 3001
      containers:
      - name: prowlarr
        image: lscr.io/linuxserver/prowlarr:2.3.0
        ports:
          - name: http
            containerPort: 9696
            protocol: TCP
        envFrom:
        - secretRef:
            name: prowlarr-config-secret
        env:
          - name: TZ
            value: "Europe/Zurich"
          - name: PUID
            value: "3001"
          - name: PGID
            value: "3001"
          - name: PROWLARR__POSTGRES__HOST
            value: prowlarr-db-rw.prowlarr
          - name: PROWLARR__POSTGRES__USER
            valueFrom:
              secretKeyRef:
                name: prowlarr-db-app
                key: username
          - name: PROWLARR__POSTGRES__PASSWORD
            valueFrom:
              secretKeyRef:
                name: prowlarr-db-app
                key: password
          - name: PROWLARR__POSTGRES__MAINDB
            valueFrom:
              secretKeyRef:
                name: prowlarr-db-app
                key: dbname
        livenessProbe:
          httpGet:
            path: /
            port: http
        readinessProbe:
          httpGet:
            path: /
            port: http
        volumeMounts:
          - mountPath: /config
            name: prowlarr-config
          - name: prowlarr-default-config
            mountPath: /config/config.xml
            subPath: config.xml
      volumes:
        - name: prowlarr-config
          persistentVolumeClaim:
            claimName: prowlarr-config
        - name: prowlarr-default-config
          configMap:
            name: prowlarr-default-config
