---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
  namespace: prowlarr
  labels:
    app.kubernetes.io/name: prowlarr
    app.kubernetes.io/instance: prowlarr
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: prowlarr
      app.kubernetes.io/instance: prowlarr
  template:
    metadata:
      labels:
        app.kubernetes.io/name: prowlarr
        app.kubernetes.io/instance: prowlarr
    spec:
      serviceAccountName: prowlarr
      securityContext:
        fsGroup: 3001

      initContainers:
      - name: fix-config-permissions
        image: busybox:1.36.0
        command: ["/bin/sh", "-c"]
        args:
          - >-
            cp /config/config.xml /tmp/config/config.xml;
            chown -R 1001:1001 /tmp
        volumeMounts:
        - name: config-hack
          mountPath: /tmp/config
        - name: prowlarr-init-config
          mountPath: /config/config.xml
          subPath: config.xml
      containers:
      - name: prowlarr
        image: lscr.io/linuxserver/prowlarr:2.3.0
        ports:
          - name: http
            containerPort: 9696
            protocol: TCP
        envFrom:
        - secretRef:
            name: prowlarr-config-secret
        env:
          - name: TZ
            value: "Europe/Zurich"
          - name: PROWLARR__POSTGRES__HOST
            value: prowlarr-db-rw.prowlarr
          - name: PROWLARR__POSTGRES__USER
            valueFrom:
              secretKeyRef:
                name: prowlarr-db-app
                key: username
          - name: PROWLARR__POSTGRES__PASSWORD
            valueFrom:
              secretKeyRef:
                name: prowlarr-db-app
                key: password
          - name: PROWLARR__POSTGRES__MAINDB
            valueFrom:
              secretKeyRef:
                name: prowlarr-db-app
                key: dbname
        livenessProbe:
          httpGet:
            path: /
            port: http
        readinessProbe:
          httpGet:
            path: /
            port: http
        volumeMounts:
          - mountPath: /config
            name: prowlarr-config
          - name: config-hack
            mountPath: /config/config.xml
            subPath: config.xml
      volumes:
        - name: config-hack
          emptyDir: {}
        - name: prowlarr-config
          persistentVolumeClaim:
            claimName: prowlarr-config
        - name: prowlarr-init-config
          configMap:
            name: prowlarr-init-config
