---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: prowlarr-config-secret
  namespace: prowlarr
spec:
  encryptedData:
    PROWLARR__AUTH__APIKEY: AgAFXdjl0IrPJHkvZ3mxHxCQfZTq6CaEt2Ce6szei1j7pyFNY3JYkJPFr1jG4UMHqNWcRYe0QQHKuiGHYF5r3eyg0aAH/XQ5c1nCg93U6gHwDCq10hiJaaUpxWPXx+o95I1N91e0HUYrF3s1do+t/FwmB9XMOQxQkAevQhfNl0wTpzKumX+jUFKXt0jvKORdxpn4jyOZp/vrb3KTrwB/5q0KV9ucKIUMi1yLi0OPyGY31nNpGZab0E4/5WJd4QyGijQinEQyA47eqybFwrSyJwH0lI6O1cUizJABcgPFIi2WKNJRhV9F5ANUxjA/XZ55W1RhqsV3bQYwAoWDvycBIjBdhZTPf3Zjpwa4xOdmVWhYBTq+D4xY+8yZSbhIqTRSNyd70jAQR9Xbsdw1pRYQ5PA2a+kIHIASj6mWKEWpdwc6vL/XstLVGP8/sxhPG9hMSpTXRbrThUhmazjBBwEmEcdI5Se6cs8Zu47DFcnFL+A7lp1y020SomESFSwiWBatyg3UOS/V0ScHcA7gBJioKtRD0bPx573SE+RT4SrnBXg63PmkFoP7QbsLiJ90Y6elkQD89Pnv9rOvjMrsxxWyEpBjg5DVlLCoKJuxlKarUZKMTemLKcEgEXdl1IgCLd8X01fIfZZVYF5Bcq1Mhc1VpMJUMT9jaQZ09bKLBI2L8IqJPutynrqSAzk1U8afUp2rYDcfjLltW4FXnJTZxA3e7GHhyJjVfS+VBcDOuJ2yvCRKuw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: prowlarr-config-secret
      namespace: prowlarr
    type: Opaque

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: prowlarr-minio-store
  namespace: prowlarr
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgAE7SfoohNHAfC4aCRxzonVQMc6ClzQH2cCePQ48f2gl9WUMTSwRB83t/0DjoqhaY5O3OlNXAq0tmZK0LA2OWqis0GF3V9/sQxcFdMXzm7VXTvgpTF4bA3XqJjmpIS0LM7cL67+k+gwkSQu1isl4wcCVmpumCrdKMPjmfBT57gIDlcq7anqPpjwEp961wGYAmFg7G0R6bnJo2GCThixWgu8oLzSFkJaVZxwh/xhHxmigjPW74Hzb0rKv4lsEZo36g2suFQOQvgdB1hnUXdOE2XOmEm0pNjajnVvdnSaPa0lPbMU5M58CVTiXVrOsKfPwBiwKdL6GHBXyvw2LAEVRsPrXdDk26pbNnQAJhrZJrZarwOjO/cC0/QcRLjxThT1ghmCm2dKR2fTKGllOF0zRBdDOP+IumKX36fWnGtVnPcj/9oQa/wZmydY9Gmz1CIOh91zDzDpoFu6bWYtyODpTPp6i+sHgy+hnzSrAWT/lmeEu4QqSRRkQ10xs8cATSqGh6imE5d1jZ+bZCMC99iXvSEn+ZMfCq8cAT1uHz9WWEUkVpRyoX6AjpTA0OHBxU8vEDYp9Jo3vXLg/e6aPvi1WkpcfDhvwhyCMu0NdPOMlbiu/O7hfFA4TGLSQMqk6tJDnI3mxtryud0gqBxbrdmcsgObn9GIpM6E9gubYimpM3S/gsfe3TgqsnhPgNKx07vHsngCfPnT370UxltnS0P2kv64h4zR/A==
    AWS_ENDPOINTS: AgA3Airuuh/lB6JQb0xGuTYYJasYFVjgaFnWmKTLFwop3R2abWWJzASQ8xP2Tf82DagTqK4Z/9bL2sfABZIJoPzYQYTY661iIRc3TK0NTodOdHns5ZoeynKq/UOUzIqEJsv7WoCZlzPQwy11YCm4Ta8nMEhYKTwo1PzEscsRfZXvwspLQIOG4qo8Gxbl3OSCunLRxkVjv+jFjkMhczWZtK6AFtojn+2ZysdkqLIvw4S2iQBvnhxmEEyKZ3TXX/MPEkIpW1tMB6+1E/WKA/kHExbGJyXUbbKVc28eWTlMHNNirjZpUWvealPGwW4Bk6hVBseKzqXFFOeyjYYybhfvP495UoQnjKAAJRvxEuQQtJGUuijSvGOsDiA995jOyQB36CZT1SotcDBZnzgt0kUrkPptgOM4ZPWmEqwdgkH/KJ00QDjdZYrDFRkDl+YNPuyjPCPAh/RT8Nt5cVnd0/QTsb2dXerXQp1dTFhbPKmWi2vQ7fldYT9aIhV/2OKGbVoqpxuAMy+NyyjtXaJzdW2qNNvQsKyVuCNKwzQ9zZVu4/1O6fCn6AQbHbENxksTu2aYrVk8ENJ+SJGJsBF5JwCzEoIJfnYyk5Um4wcBFQG5T3WPhX7xwMPp9l9p2OHIM1kULKRWbPodxo+EP+2VGp8VIhXJJ0L4zbVIiyxgo7RY63ShvqO4dvg5CT/Wc5GUclWg7UF+buvszp2H8EW+meopFrvnEmM3geE4zXMG
    AWS_SECRET_ACCESS_KEY: AgCBfONPKa/jthMQhKSbVnNt4swASuI2dW2pwUuBfBzVlwL20dlwoyYXzfHAD4pHtZJAm4OA1yUYdHyZJvvtJCtzR5wTzb7kwTDVTa1uCVw40XnwUqnpPM+9PnZi2DL7L5Cla+T31y0Z17Hlw66myqOrlEYhozDtDHG/cfaA4C0tj7RVUIL1BD11Pp8ZNQ3rrnCK/3lwkjaVfHli8BJotLqyCFwqtWKRrI5pKUCyM0/Fh7HWXEHh4m2OgXvhg9hTlvfS+MD5KpEDPJpnV74ZyHfyLy2WFujzhgqi6IhPcrL9Z6SgDKBGg62njEdzacnbGnbl9U0febfYaaoCuf4AQzH1RxiDAB8PgsH2HLt5A6NVKeoaZsii0eWcFpho6uFO/wUTVFLkU/lNnbr3V1dBXDOkqyDURfwkNVsNqz3iLIQNll2RpOKv08p8vDw0so/6f5EkR7p0z64bB/rJqUGt3AJWrgSMk/2zeOjgdynN8R+BMrgo1/yx5SMzxVduu1j+zwYHfo8RmJIM4TjsZAZMmXJxw0OgQJkinpji41g6wJlHRLOUOFh1TMkboPq+mnXpCMPj5e3gB/qA98Qx/OPEJI3hcllkDXW/Qjov5RZQhglxA6S/273S8OV0RDpJn9UUR5KHb9zli0FKqMRsGcn2wneO6cSCoUX7nBK8A1+T2aVPHuVx1paHswNoVStDshJGbMktKH2GDZPd8hl021YlynZtlX5aaQYn+9CEKVv0oiq/O0VuFdhK2ZzN
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: prowlarr-minio-store
      namespace: prowlarr
    type: Opaque
