---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: prowlarr-config-secret
  namespace: prowlarr
spec:
  encryptedData:
    PROWLARR__AUTH__APIKEY: AgAFXdjl0IrPJHkvZ3mxHxCQfZTq6CaEt2Ce6szei1j7pyFNY3JYkJPFr1jG4UMHqNWcRYe0QQHKuiGHYF5r3eyg0aAH/XQ5c1nCg93U6gHwDCq10hiJaaUpxWPXx+o95I1N91e0HUYrF3s1do+t/FwmB9XMOQxQkAevQhfNl0wTpzKumX+jUFKXt0jvKORdxpn4jyOZp/vrb3KTrwB/5q0KV9ucKIUMi1yLi0OPyGY31nNpGZab0E4/5WJd4QyGijQinEQyA47eqybFwrSyJwH0lI6O1cUizJABcgPFIi2WKNJRhV9F5ANUxjA/XZ55W1RhqsV3bQYwAoWDvycBIjBdhZTPf3Zjpwa4xOdmVWhYBTq+D4xY+8yZSbhIqTRSNyd70jAQR9Xbsdw1pRYQ5PA2a+kIHIASj6mWKEWpdwc6vL/XstLVGP8/sxhPG9hMSpTXRbrThUhmazjBBwEmEcdI5Se6cs8Zu47DFcnFL+A7lp1y020SomESFSwiWBatyg3UOS/V0ScHcA7gBJioKtRD0bPx573SE+RT4SrnBXg63PmkFoP7QbsLiJ90Y6elkQD89Pnv9rOvjMrsxxWyEpBjg5DVlLCoKJuxlKarUZKMTemLKcEgEXdl1IgCLd8X01fIfZZVYF5Bcq1Mhc1VpMJUMT9jaQZ09bKLBI2L8IqJPutynrqSAzk1U8afUp2rYDcfjLltW4FXnJTZxA3e7GHhyJjVfS+VBcDOuJ2yvCRKuw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: prowlarr-config-secret
      namespace: prowlarr
    type: Opaque

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: prowlarr-minio-store
  namespace: prowlarr
spec:
  encryptedData:
    accessKeyId: AgBenV+Di3toSh4rKXkyN42U+WoDDvOqCNTNclb5O2dTiKAWdWwy+ca/uFUoBkUbGacUPtEIrKeaQCixJqwOErdN9h7mzNYXUBLuH5dxHDiU/wakmB2i+nJ6jGkjCmvBiEilg7SdC2VgoD48DPRVFiRjQ3VuyYRb24kbDwte+AksNt11JIG2MnOvFn02S73z7XRZPUJCKeTFsDsoX66t+t8j28kH50hFi7IyQH2X8C4VaKw8F3MmNOzBstTq/gVhZof027dSN/gukegn8m/2pR7MeIyzp6cIKIbBZkTnlJB8E7o6w1odtqPtfBCy8w6+VZPpKVsebGcB22tn4atFv0UnlFdQjVeAOQEPDU7BmArIRfhDTxzHUnD6/x6BmAaPMEIQ/KbDq5O9fInkdCYgDwnfX/RMgSJUGza1Ij9Pd6ppmM+DoO9c83YHZ3mO4EeNw7O6TPBFTShGX9fq4gqc8+1cMu2FEaZeQ5QYtyqSPrYH536H45ow2LORycSQxRpChu+5oR2mRd9ZWSCnKyf2vuU5521gjE2CsLLdoUx6WavAqSZQ4XLwxd63poof4j5WuIhR1kX5rHGiA+aBuolkWpaBb6rfX8YKoQS6yOOGaWXKf+KLYmjctem6FBgUtdymNJBKh255GXeY9BPlgMnHs1qBTvYwr4MvrYotACdu0l1c8u0yY9js/2j5obCve1GtOupGmAwscZTp0/bv3HSHU2s=
    secretAccessKey: AgBUvk+5jYJzAQ7nSa76f5SAvyFL/yffkOOh2H93gpwB01vYz4nWhZbfvJ/lUCbDqJZkO4NoIGr52KgXTSa0FUEvuftpiqMI2AbjrFDJSkKFiXufSu+U+ur2Syl1ntBuNd29qqWr8BGmqbjYYg9OxbK8J+hz0ZsJ1R+zGVqBONyVRqiBes38h4BsDLC+HQjfbzeSxXhhLc64sYDNYsE4UGHIf7uT1wTzIHARqmCCXMH7lgCO8XF+kPMS+ZI2sdvdEMjFD8+jKcM0W00xWTQhqGOML7+/J+QnNbqWaAJXa7CVIDshlyafxLEhzBIWYDOJMFrFNZu4HnZDGLiXEJuq+hHwslE9MXIBNp2lJcZwsdf+RR7HVZCpPY/kcFAVK5bfG3vgvWgbveXsNsyA3VhAVZB0QY2C564FsBhvG3wSnHIUnol2SMvysrtfjpAxiecDqz3t9xBmceFShSDqHuzsZBFnNThiWk8iHG0BOxmmp+9RRJhX0yRgsmqoVzO7d11UjMbEEP10vgkfFNg3jXZCsAPLy1mWFiOgMxqBY1iBEXN8AWIWiPrrQ/BXyodY/hXIHdynGCt9hyWcVrnLx4T1DiNLUd0ySZmvedueuLgNKO+IHcOZZQXvQLuLW9qvJisEdXQ8RDxS3lfVZK9o/c1yLKF127FfhMi2MPLOTxmEy2mJ3SU5L+jM/1vKDjKMlNq4IQpNqalMhEzynlEnKoAH/G1yunl6JYPVHgyz6U8Fw9Y=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: prowlarr-minio-store
      namespace: prowlarr
    type: Opaque
