---
apiVersion: gateway.networking.k8s.io/v1
kind: GRPCRoute
metadata:
  name: argocd-server
  namespace: argocd
spec:
  parentRefs:
    - group: networking.k8s.io
      name: external
      namespace: gateway
      kind: Gateway
  hostnames:
    - argocd.lab.schaermu.ch
  rules:
    - backendRefs:
        - name: argocd-server-grpc
          port: 80
      matches:
        - headers:
            - name: Content-Type
              value: application/grpc
