apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - argocd-rbac-cm.yaml
  - ns.yaml
  - grpc-service.yaml
  - grpc-route.yaml
  - http-route.yaml
  - secrets.yaml

helmCharts:
  - name: argo-cd
    repo: https://argoproj.github.io/argo-helm
    version: 9.2.2
    releaseName: argocd
    namespace: argocd
    valuesFile: values.yaml
    additionalValuesFiles:
    - patches/helm-registry-secret.yaml
    - patches/oidc-pocketid.yaml
    - patches/redis-secret-init.yaml
