---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: oci-ghcr-helm-auth
  namespace: argocd
spec:
  encryptedData:
    config.json: AgBDCcCPJD1GJfH1Mphqwwyoq/1fQf/STwkuvClAlgT/EvwW6OcFbFF6WZVBBDLXKv7KPmY3UtaTqCDMqP7u2VrpBim+4D+PErcxVhiEuPDqYlIbN8vutyilTtqKwIlyIxwmKmMKK5Bu+aZkzRMaYUiaEUo857E4lmqiUYsrWVEmKOCVmVnxQt3g3oA3prOUy4O2WmB1B8dmRKLxJBCF37phjpr6crwtxhLLbcEYVYe6ZcRSq1EkYVVNn/M7a11JRaOmdb3KqI03xUVfsoIsDUZ/B4dM4jJ2FBIYWOiBGmwY0icFx11EA9VsWrFgiAIFa1ovcN3LtkoAJeFdkdJ3HvY++bSY5QENDr78Q1Yq6Nh8Z7naQ9ecYHoXU5Ik43Hm6Qs6pNz7uEZGwtUzE90MDqZp6mLsBXg2oBEHMklxg/7qPteg47JoMk+2hk4830mFxuy24JD3kn3RMtmMK3Zov5bYRLHCHWCo+qiL+R6vRzy2Fb2fLXl1OYtZtvD7YWB/1LZM8dkD3WkmpkOMsOFZ1s4hK8aMl65Tnyh4kAtyS8plSxE45mQrKhNUypdOzOKonapqTlCCUK4kVxzsk95KgW2YkL9WhnisIdKJiWRvVHH3MT9ON/NKXn5SCvetFi/6yJ7HH7lldHhX0OWBr9ZoOIgW1g11iQiZsRt2zoUGWqU2ito1W4Ti0Jfjv0LcTX82oeF8+u7q3xEfCkRsaWbAHlPFlK5PggvjDSVkbSHm5hKdqDFmom4/H7Wj6wIC0RTrRr1KmFBdHC+b5fC1NjBCAmOxW9Hx7gc5GNqkQMMZMcZ8ApbNGP5e6Z5Gqm2kgNR/0faUzjLiE8/eBhxmfCcBDvmLuFLeQVoeeQ==
  template:
    metadata:
      name: oci-ghcr-helm-auth
      namespace: argocd
    type: Opaque
