---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: oci-ghcr-helm-auth
  namespace: argocd
spec:
  encryptedData:
    config.json: AgBaZ2dcXborM6xvudh5ZIfFI8xvvDzkS+gI8MrBmc1BqPVdW734TvTya4LlIbs4qqmG052YY2uVpXcdqKXfpQd2g7qZia4XcwUm/ythuW7hYWC3RcmDW/78gG+SHsjKOJ1IDUWbYskDY+gKtKje7Y1mWJnfbprt2bAAQZc2acWUovfgldA2EVwh4VSjMmIwoTGMPzbVNovYJQIWkHx2I9Ae6gVooTLaqxnk/Z1WC7gJLQJfD3U8i1YSTa4HrsFaN0qHzFUQnElzScIJd2/t2dsaBVqv9txitqybSFGIqXkKq9B/yxdV0KRRRZXLQyQidSiA3tcUXNsXqjIhi2dQSQrKKvoKbRQcvmMU0Bze4dJrcVd2QU2aA5d4ylc/+P1Jn38OmH7b0XtBOm//DpZF3wXRL5AUBchG2Ic2bTKDsyMk3cRLduIAZGtcj3y8zkKkH1p+9ifgl4GEOWz/GTe4buNuW7a+ApLMvyGbLP3HNOHN/DkghAUDYy7dag9TV7bD819IJtlFShuvJWlAjURoABPFqSZu6FS6zLiOGXmJVbXGzpUwp/jj/zygO9DEhA+zgwL8J8kkS8x3GeYGOqp/GF8LK6fIX/AmgXdtKdByUojo7kuUeJmVii2Gyt0/t2m+eChitf73ZnRD3V6W3V1V8qsKafNHI+xN3IBdHHcvDRHFPvHIW9L/9gjkUPGo7GEQ4hWVT5iBzlftOO26BHfA+sSxs414nN86VWkbb+cRChzIRqxi4SoK4WD0Rvqbmuedy9fx0YDXSJkxWR0fqo3BgHBaIdw8e0kULyiTZ8jaiHoGiiYetUxJaqLjwdNT9wI1Tkb//ffu5bBscDFobbw97zU57nslthnqdg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: oci-ghcr-helm-auth
      namespace: argocd
    type: Opaque

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: argocd-oidc-pocketid
  namespace: argocd
spec:
  encryptedData:
    OIDC_CLIENT_ID: AgA+sdfqTjUEVV/ehFkNDRJ8MT/+PAgB6CtWhFje95IY4oVcRYMRwe4OHacYi082MLFJgZt5vg353LZel+3Ye/lCONyuyqCEMfFdzFGiNE3VpgIRoo/6kv5cJ2Ssbnzu/feFLlw7vrzE3zcpBhz3OICMn7ghdHvQiP9dwWoj0T+Ws0ykfpiUqmEkr7x/Ulmr5pmvFhUs+HGeM2Vl8l8ZOHbbxm8mozzuD2edaOhF7niW0vLm874YycryWYu4D/oA+Ebqy7rv6ZSEJgreQkDgrCq5aLBEtVu5ia8Vf2K2IPjnS7Dzp8Dx7yHMF6QaT0w+/5qQAr8XsZRhFOdGwQZ5N2paQhYY35Lu+huLk1xAhWeK+r3xROP5BSpWH14OrJO9xcitareA/ojI6rDK3J0yMlvTtSuXj72iI/x0QbkEDKJSPG2QsNZXjVCEIReSiQ1gKMd4lpNpucx9gf3Fhtzdk3NxEOpBfQ5z7gq/ty6HMHaqXC3sDKq38Zf7sFINy53lo8Skv0bRkUl5HRueaBq3yJWB+48py3hFlQ+Qa7/PbWQHq3Mg+pPuIhB1VnXHBu/ncjHwsAiHdVvsIoG9UR8gqKyd5dB7zWssxSDGCZpYKTN0HVCU1NPDBwc35s7e1OZv1DJ96rHbefE+FwatjOWz59zhHM7jYMqwFjREWNi8bE8xEToZEUsFeqSR6IymurjpPBTjIrXa4LVGb+qZtL5RdEX3jMVP93Mik7H2UoRep7TuwmQtkBg=
    OIDC_CLIENT_SECRET: AgCUhxbMiSL6WvflMufx/Alg/HH3MFjImTVK0Z26JTMU4mJK7qw3FSvKPcDGvUgoEWQN0OVG3n+nB9zoLWDmyHgqi2+6+PmF4N9doDAsatlNmQ+JzeJ6npxMGVv5TjErDbVS3Yq/QpwOmHXQslS8x2nwpkVvApddu+9PGerP47+JUm6P4C9kI0QIEqyymuAdNm8IzuFhc8kZcMrP+LhdqKNfzbO0aGS9sbwfxbKx/Dhu3EZ0aXQ9vcdIkgaFf43Xbzi6urgMg9Rj8TbGuh6v5+KrWXzv2zPsBPDyxVJ6dzCq0gE0wKDrvEVG+v0SkIFu4buvwCa+cxfkc6BEx9Nf7jtNqqShxXJo5pbqAPEw0upAv9hH+Haen51iAl3wTi4y2gZGcVArABegtwooRMIaFq46oGsl7pUkCm0BUXyhB2Bd9gIBQJiMdc8QpVYn+8IrsFNEtG0BhSuTbO6HEBItMPiqs/OFrSWUvKtMAh/4o3Ocp8OE2tbtdj6Z01oiXcQGom6IPNSvrUG/t7cMGXWX4Z+5PWnbs+utScDDIymhb/T1V5PIrtW8ariamOQaBxko06nRYCHGCUMfPAbWR8rz7RzQR3FGeWCxSMJzOXurRxAX2IDO+FDEIja9pf7EmPFXtpZKCmOFS7KvOYnI4tIeu+tpvVWKlN2OCUe06n+HIl+eFjzVSeKVoZZHxPsQftl1xI66hMvTP+4wrIzkMmx5I+cYWTjIrhwtMR8P9ArsGaJUPw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: argocd-oidc-pocketid
      namespace: argocd
    type: Opaque
