---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: oci-ghcr-helm-auth
  namespace: argocd
spec:
  encryptedData:
    config.json: AgBaZ2dcXborM6xvudh5ZIfFI8xvvDzkS+gI8MrBmc1BqPVdW734TvTya4LlIbs4qqmG052YY2uVpXcdqKXfpQd2g7qZia4XcwUm/ythuW7hYWC3RcmDW/78gG+SHsjKOJ1IDUWbYskDY+gKtKje7Y1mWJnfbprt2bAAQZc2acWUovfgldA2EVwh4VSjMmIwoTGMPzbVNovYJQIWkHx2I9Ae6gVooTLaqxnk/Z1WC7gJLQJfD3U8i1YSTa4HrsFaN0qHzFUQnElzScIJd2/t2dsaBVqv9txitqybSFGIqXkKq9B/yxdV0KRRRZXLQyQidSiA3tcUXNsXqjIhi2dQSQrKKvoKbRQcvmMU0Bze4dJrcVd2QU2aA5d4ylc/+P1Jn38OmH7b0XtBOm//DpZF3wXRL5AUBchG2Ic2bTKDsyMk3cRLduIAZGtcj3y8zkKkH1p+9ifgl4GEOWz/GTe4buNuW7a+ApLMvyGbLP3HNOHN/DkghAUDYy7dag9TV7bD819IJtlFShuvJWlAjURoABPFqSZu6FS6zLiOGXmJVbXGzpUwp/jj/zygO9DEhA+zgwL8J8kkS8x3GeYGOqp/GF8LK6fIX/AmgXdtKdByUojo7kuUeJmVii2Gyt0/t2m+eChitf73ZnRD3V6W3V1V8qsKafNHI+xN3IBdHHcvDRHFPvHIW9L/9gjkUPGo7GEQ4hWVT5iBzlftOO26BHfA+sSxs414nN86VWkbb+cRChzIRqxi4SoK4WD0Rvqbmuedy9fx0YDXSJkxWR0fqo3BgHBaIdw8e0kULyiTZ8jaiHoGiiYetUxJaqLjwdNT9wI1Tkb//ffu5bBscDFobbw97zU57nslthnqdg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: oci-ghcr-helm-auth
      namespace: argocd
    type: Opaque

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: argocd-oidc-pocketid
  namespace: argocd
spec:
  encryptedData:
    OIDC_CLIENT_ID: AgAVBTsfJM8e4QtwTOBhxD05iInWfTmZdDJlxib0kyAh1pGBDqtzw19U9jxnXgpCeR0FEk+el85XHy4qfWfI4zh3GIiW3Y5vivGQ/nvP1Ioq67wtc7fqB5mJE6LnfHSVyVna/nCt0Ohr4ym8oTga0gAPRvWEPaN3MOas5VBIyduhzKKU10tBXQ45JVH/i7U9K2B5WXUwYXtVD7q9fDh19wli+u4qmIDl4WlzWM6rZZiLe0Z/xymUzqeKwTBV8DTkXe8L7jrqgc9uAko3GmNhK3YEbs6jfkhVXidxU8jB2/G1L9SsUKfZtzkeZewe1IDdU+SK8PWgF1YZ2N4v7D3T0bqHa4up/BmdE3l1nc2mwEQZVvIJ81Ql8zcVul1iEoD2CpcBRZQFlOD1kfJM36VWiPB5yt3+jK7QgIzFQU+EhlCW3yLFR4VrAm45aNMNLfa2tnr/hAhzVnvPP7VaEam4gFoy+hh5l5SKxZQjT9ZqksalftMIEKgTIf7cHyy9pzW7mSxnqujOE5TCmDGLm8jjIDalF+srlaodwROhE12NVSz2ufumO6Wd1lY6xVzE0WVzpF8CUYil+j9j7R0yLyW9GUnPUqlF0HDWjLV11zsd6n+Wev2BcPKhwyteaVEe6yks83QPie72yoWTwKEh9cwXEtm0GjqhItzKdXrV1gIS/Z69rUDndOZm0+UpxtqAheam2+UHObDXsxX76ceThnWSKGRfsMj1PLJHULuxXKkuUTJ8xu7++qs=
    OIDC_CLIENT_SECRET: AgAMjZL2fKl4S2Pf6ZpxPoO7qaYflfvF/iERcAYeDtTzRpCR7yKpQbkFSlH2FYVqx4Js6ElzGhozGYVgQ3UYJ6g/BoCgm81C8gamhhyk6ve9ONORO6D5UF1rPbxeWc4icwlZQfaSpSZyK0SN8z7Puc0E7NOUlB6zFXKcgytJjIkZcR/r3dlY4alU+xO02Lmg12vCY5d4BYnymnR0K3cTIfdrTph92LWNzwTYirGIvZeC9TN3dkOO9nrHcF8MWmPsKvmoFcuqmgmahP0MjAOa6E6HaZu7P6yT4fCtwV+lZex7cd+N69OiKWO8jAcKWiXphXfJL9hrjE1dui4A8xDuFU/A1/jL0jJw/ejW89z2PkBBdIAN2oRJvhoGFpJJAImbcEGrPRpVt3TY5kWXp7ozyi6oXf82/YyJyAQ7Ywv+ANAXC0dnQ/OVvhZT0w7QJE/KP3Rar/sBclEN+gBF6EwTiF0ByP7VTUfFaE8B/s8WyOLEI64Ui2LlbSS+LSUKXwoCjPerseYgBaGWJzFEaWqgFowIRhMYoBgDMnoLNrxE5MK/U9eUrIT5+qksxrFA9cqpVZqIY6FLsYVWerHWhsyInXRlqqEtYVHJB8KDZJll+9DlT4Z/ceMiiOnHvzy+y5TqQ1+/oygUmCe3Bs8d4fAFOK8KqFEVZJVp9dgD6rzghrbFu0hVp3gc0GSKiN9DvD805TfpyBDYZLFDeV7k7a2ovf5+Bh5MWnJ7VWckDrWlrzr22w==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      labels:
        app.kubernetes.io/part-of: argocd
      name: argocd-oidc-pocketid
      namespace: argocd
    type: Opaque
