[tools]
opentofu = "latest"
talosctl = "latest"
kubectl = "latest"
kubeseal = "latest"
kubeconform = "latest"
kustomize = "latest"
yq = "latest"
helm = "latest"
argocd = "3.1.7"

[env]
_.file = '.env'
MANIFEST_INPUT_DIR = "k8s"
MANIFEST_OUTPUT_DIR = "rendered-manifests"

[tasks.tofu]
dir = "tofu"
run = "tofu"

[tasks.kubectl]
run = "KUBECONFIG=tofu/output/kube-config.yaml kubectl"

[tasks.talosctl]
run = "TALOSCONFIG=tofu/output/talos-config.yaml talosctl"

[tasks.argocd]
run = "KUBECONFIG=tofu/output/kube-config.yaml argocd --grpc-web"

[tasks.kubeseal]
run = "KUBECONFIG=tofu/output/kube-config.yaml kubeseal --format yaml"

[tasks.helm]
run = "KUBECONFIG=tofu/output/kube-config.yaml helm"
