[tools]
opentofu = "latest"
talosctl = "latest"
kubectl = "latest"
kubeseal = "latest"
kubeconform = "latest"
kustomize = "latest"
yq = "latest"
helm = "latest"
argocd = "3.1.7"

[env]
_.file = '.env'
MANIFEST_INPUT_DIR = "k8s"
MANIFEST_OUTPUT_DIR = "rendered-manifests"

[tasks.tofu]
dir = "tofu"
run = "tofu"

[tasks.kubectl]
run = "KUBECONFIG=tofu/output/kube-config.yaml kubectl"

[tasks.pod-shell]
usage = '''
arg "<pod>"
arg "<namespace>"
arg "[container]" optional
'''
run = "KUBECONFIG=tofu/output/kube-config.yaml kubectl exec --stdin --tty ${usage_pod?} -n ${usage_namespace?} --container ${usage_container?} -- /bin/bash"

[tasks.talosctl]
run = "TALOSCONFIG=tofu/output/talos-config.yaml talosctl -e 192.168.1.30"

[tasks.argocd]
run = "KUBECONFIG=tofu/output/kube-config.yaml argocd --grpc-web"

[tasks.kubeseal]
run = "KUBECONFIG=tofu/output/kube-config.yaml kubeseal --format yaml --cert secrets/sealed-secrets.cer"

[tasks.sealsecret]
usage = '''
arg "<file>"
'''
run = '''
mise run kubeseal --scope cluster-wide < "${usage_file?}" > "${usage_file?%.yaml}-sealed.yaml"
'''

[tasks.helm]
run = "KUBECONFIG=tofu/output/kube-config.yaml helm"

[tasks.backup-db]
usage = '''
arg "<namespace>"
arg "<cluster>"
'''
run = "mise run kubectl cnpg backup -n ${usage_namespace?} ${usage_cluster?} --method=plugin --plugin-name=barman-cloud.cloudnative-pg.io"
