[tools]
opentofu = "latest"
talosctl = "latest"
kubectl = "latest"
kubeseal = "latest"
kubeconform = "latest"
kustomize = "latest"
yq = "latest"
helm = "latest"
argocd = "3.1.7"

[env]
_.file = '.env'
MANIFEST_INPUT_DIR = "k8s"
MANIFEST_OUTPUT_DIR = "rendered-manifests"
KUBECONFIG = "tofu/output/kube-config.yaml"
TALOSCONFIG = "tofu/output/talos-config.yaml"

[tasks.tofu]
dir = "tofu"
run = "tofu"

[tasks.pod-exec]
usage = '''
arg "<pod>"
arg "<namespace>"
arg "[container]" optional
arg "[command]" optional default="/bin/sh"
'''
run = "kubectl exec --stdin --tty ${usage_pod?} -n ${usage_namespace?} -c ${usage_container?} -- ${usage_command?}"

[tasks.sealsecret]
usage = '''
arg "<file>"
'''
run = '''
kubeseal --format yaml --cert secrets/sealed-secrets.cer --scope cluster-wide < "${usage_file?}" > "${usage_file?%.yaml}-sealed.yaml"
'''

[tasks.backup-db]
usage = '''
arg "<namespace>"
arg "<cluster>"
'''
run = "mise run kubectl cnpg backup -n ${usage_namespace?} ${usage_cluster?} --method=plugin --plugin-name=barman-cloud.cloudnative-pg.io"
