---
apiVersion: v1
kind: Service
metadata:
  annotations:
    projectcontour.io/upstream-protocol.h2c: http
  name: hubble-ui-grpc
  namespace: kube-system
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: cilium
    app.kubernetes.io/name: hubble-ui
  ports:
    - name: grpc
      port: 80
      protocol: TCP
      appProtocol: kubernetes.io/h2c
      targetPort: 8081
