---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gluetun-config
  namespace: download
data:
  SERVER_COUNTRIES: "Switzerland"
  VPN_SERVICE_PROVIDER: "protonvpn"
  VPN_TYPE: "wireguard"
  PORT_FORWARD_ONLY: "on"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: qbittorrent-config
  namespace: download
data:
  UMASK_SET: "022"
  PUID: "3001"
  PGID: "3001"
  TZ: "Europe/Zurich"
  DOCKER_MODS: "ghcr.io/t-anc/gsp-qbittorent-gluetun-sync-port-mod:main | ghcr.io/vuetorrent/vuetorrent-lsio-mod:latest"
  GSP_MINIMAL_LOGS: "false"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sabnzbd-config
  namespace: download
data:
  UMASK_SET: "022"
  PUID: "3001"
  PGID: "3001"
  TZ: "Europe/Zurich"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: qbittorrent-default-config
  namespace: download
data:
  qBittorrent.conf: |
    [AutoRun]
    enabled=false
    program=

    [LegalNotice]
    Accepted=true

    [Preferences]
    Connection\UPnP=false
    Connection\PortRangeMin=6881
    Downloads\SavePath=/downloads/
    Downloads\ScanDirsV2=@Variant(\0\0\0\x1c\0\0\0\0)
    Downloads\TempPath=/downloads/incomplete/
    WebUI\Address=*
    WebUI\ServerDomains=*
    WebUI\LocalHostAuth=false
    WebUI\AuthSubnetWhitelistEnabled=true
    WebUI\AuthSubnetWhitelist=192.168.1.0/24
    WebUI\Password_PBKDF2="@ByteArray(ARQ77eY1NUZaQsuDHbIMCA==:0WMRkYTUWVT9wVvdDtHAjU9b3b7uB8NR1Gur2hmQCvCDpm39Q+PsJRJPaCU51dEiz+dTzh8qbPsL8WkFljQYFQ==)"
    WebUI\AlternativeUIEnabled=true
    WebUI\RootFolder=/vuetorrent

    [BitTorrent]
    Session\Interface=tun0
    Session\InterfaceName=tun0
    Session\DefaultSavePath=/downloads/
    Session\Port=6881
    Session\QueueingSystemEnabled=true
    Session\TempPath=/downloads/incomplete/
