---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: gluetun-config
  namespace: download
spec:
  encryptedData:
    GSP_GTN_API_KEY: AgBFUgSgv0UhmCpA+RhgOcs98QTuD6q2QYL+ZWzjfYEp3gnp+syJlMpWcF61+duTt/I6CntUGzsM6YgJJf1xhfg6jqmOpwc9OPpeyEgWy7MOOkjS3lH1pCGFCiKij9EO5HGiPumtWYvdEx/javvu/knJemvtbMSNJU++3o4lygQAffGdNKq/o5KDTsdlRYri5yRoabPVVIoaeGKm+HVHJhpjMkftjfPZofUDTHIox256XIc3AFf+wOk7EE4B6nBi4bRnt4TFppgMHBDlQWcyoseJx++27USZGD3NB1fV34B6Y5ebwTxWKRSmJkHTODut7ygUZpkI+tKNnh9PkxidbLszhkZ8MtJdK907T/B9P5SWm6jiHFxfPQSLhogG6uBeAtYYdLjK2PcCZ9+e72sOJffECrJVJGSvjiCiIvgGxj3MZXYWCQzvM+sOkMY/KnyBHLjkF3idYW+I+LpcKs7QmlbdXhNYsPARB+qAF7ZfIkzTFefzYaMqJ94paJdTTs16VLljetwxHXGNLV/92A3sGf1mFo5oSn0Or/HczRajuiGN/C34B5yXoAMu/PxLFRRgcU3MFIvmXmefgx7V6QMGApJkHB147XmW7QX+taVWghHgu/JCNPEq+8k6vDrxyNAXDrLYch0ANmlMIuNGjYVr8Oj9xNcEG5h62GzTGHNqXlaSmyiPbXRY57oPmps/N8cX4wHPu2E2iVDe0Wpld73upYxfn7TU4WzUzxXPOmvtEcJHwOdf1ZlP7rDXtG0vJyamgcOHtY2G3PPE/XwxB2y2/IgTbFDphg==
    GSP_QBT_PASSWORD: AgAGj4DeXXgaWHdEu1n/lFVTAELQax8BLgHszUJZ4teM0fy6eL0VxmEf+/w3U59Z9yujTv2VImjfDIYjOWt2fXALdUVsBfmBAMPz/wI1dG8qG/5HmWSZGJ9abHeTO+BD3CNiaHAp8RT/jBTjIRk8gts4gA6c9eh1iqSPBfqaYDn5aVFjs+tktg8qxbCQVlvo2KP6xEnc8cp4dQRBWaWZCakjIMRwupr8Uw1knJ2hcKBZp0eMhFcqeQIoTLPCaEGFaCi0BqjGWhNjEAMjav7uTUEWQAIZTDvdVHymY+YP5v+6fdVIDrP8L0hZsqTVsXeCasJoj9vjRz791DtW/a1XPEcgSA7J38V1NB7P9ER5HEzIr2wXOirbqZ7FnPIH4seg+xU3nmZ8GpOHaTlYJICSVra0aB2dX+LUAR9Y3hefvT1yTrSVZyNgEc8tdoBPJiK7kvGKFYEpBO6kXAN+BzPYtbY7B3TPVL13tz/CQazwB90ZmiMm3rpnzDBMRctOqjta6PtEdBCOnhiaaPo/kuQBxKK8kVUFP7btmNtVTHcCDCM9Lwhq+CPgAHigt9js7k/pHjLMwhirJm7Z60yI2aMkp5+UnUK+dpZBsSN2g86naqqxqKHklM7EsyFRGCU4pUG1ezkcSu2x2cel1H41M4bcrPTrI3/tan+uDPRoukJD0+MYFEEf8/woDBZX+4KrkwQudVvvHl4AB0/xJPCp
    WIREGUARD_PRIVATE_KEY: AgAOIBFg+SxrtvPVPBeu5/nFNRzC3mfbwwzqB3UKT8lvEjreNXRYcm1BKrEoZHye7lpiSX7qM6zTqQmm2daobigeJjv7mw0h7JnbjyJMcShFDKQKkrdtpkmg5mNyPDAIL1EaKCRQ1ivGLwhRpetykrXZckTDWeh7dg7RRHLEjdKZhjBXn+h3FmOtgMIeWMGEz3EwZ3IlqLrqC4ofk8roJ8QVBrfDCxkltl77n1zuy8YOtIcjcQscl3aXEDIAf6M6OIc4O7Pc9XKBb5XX755WmKxg8yuw2cvWL7RTrLvHC8vpehx1GkEbFqdX9W2m5jNgVw5VLw5fF0VCrKOCsuQIaj3MA/cigL0n0V03Oi2YPSlW3FVE1hegX5McwktdRF4zKhYme6R1duhwY5y2Z0wHNm7XQELPYcFfqvIVgeNTX/mGtsbLyUD5KRTtgyhv2oe5nERaKtOSU6BT298XsGxuyBd30Bv8z0zbEXea/zp8e4IZ96hpAQeEDvFULC+wYltr/l5EDqDRJJ2pqGtDzWJQVcPSvxNbZp1mgak2vc5jUQqObbUJuDAtBODqnQNoldlNNRTt/bfF8hMPRpE2p7Vr8rrvNi3DmdouLmjoTYDdSR/W/MNwtWYKsa1jf3+6B07Ud7mNng46RnPqMgZE7sZOFQZOS84eUssZGdBpZ36kVOwG70ERfy7PCMkafu8ksFL77mwirjq/akWNJ0Jitz4Bmmn+fBzmvSiDFA3Wlsa3E56zWRdzxbWfX/x6erM/tQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: gluetun-config
      namespace: download
    type: Opaque
    data:
      gluetun.toml: |
        [[roles]]
        name = "t-anc/GSP-Qbittorent-Gluetun-sync-port-mod"
        routes = ["GET /v1/portforward"]
        auth = "apikey"
        apikey = {{ toJson .GSP_GTN_API_KEY }}

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: sabnzbd-config-secret
  namespace: download
spec:
  encryptedData:
    API_KEY: AgAnrNdHfJlILeCt6X4rfqsL2E7QY1kI/iP3JX4RfCDq65KqKEpJzCngR7INKfhaxFRbbh80ZEnfwiv5MpjFhaR3vzkQAr4nM2ZiJ+hxFY6d+eV9MivfIBOplgDVAZuujdptrOrZMMGgZcqhqKzJezzWVg2/yMEsmpQF/c9icbg6114WJ5TOPyO8uwpP6XQnooU10qs7N9sMhYGAKK3gyp5/drcQjhnVTBDkUh39SFUEJUGLkKvRs17Vw2b1IAryNjgxyX5BkIsiFyBzdrZtfJIGXT0GaHUW6lxY9dVQth5vTZn7DP07jQe8hED80N9MOiOQQ3xUlSzbgJbg9BTyEGmwUumbYG+tA8tmyep8VFhTOz7KlkLUa4V6PHv4nEMsS54/igjGD4oW540L6/SvNjMZe3XYgVU2+pXQz7qrrCtaF5WUK4YXMYgry8B+0MdikyGrzMCVvBjs3N1l3Ch+Gsc5QC7j23J2HisHsYodNqGBQIbQgXwjpQly10Inow4LRigrDTmMBaaQ+/4SMXPpb8x6L9rawAn9jbjh09Bnx9l+pYjS7cxi/7arV8pSPBlogX/SRbUa+fDvRyCwkisYPqlQwdUJuhF69a7M92xW7cBh7RGg24KHi3XlM2Zo4Fgo16vaB+5dZzamq0mFrpGvb2/5VE3fw561FMNgngS867sWtdgIg7shA9jmTGhbVAU/7UTYzH83W0R9aL4FrdwJ+yHQqEXzOjUmIIU9HzA7muKTFQ==
    EWEKA_PASSWORD: AgAu2Wityq0heV8sdhVIUQItIjumN2B7yaQQ3fmQydz9EgTgh0FbPIvC2cXTpZJYlPThJZoj5+E/YckcUgce0eHIR+aQDy/KpzKBRbcI7HNpdFC8r0u3Q4URXkrKal+YIH+u/t06KkyiDHkdlSHjlrRk1TpadEhwxH0IE0Qa6klruDrUrAEW1rEG/H0UNQm/Khix7BhS5UvXMSu4ZIrQ5ImvXE0F922WXoD3Br5uis1vCgR2S2C8AjMhUaIAsrzyqtmGHF47MtQopH/mSdeyIa82BMS1RgqHsGrrTA9sgmwSykFxwuz/RkWzBMXmNET1q/m0/Ei51xqztTcUe2N7oJQ5T/0jPg7lFIAnGnT1WIYNKYplAkYeyasFe8u6KPT6zDNFYlxA5F6BS/KLKz9qWCuV6xf8TPJDrxALyEGauEE6p/s+4roqC51GYpVJQ5DvdPOodBVED+d3HU4/CJbigP33koAmjpR+a0Ddn9PGc9DV62/ziS5UCn15v9wVle8po3tsY6qt/e182a75pBLx+K7mvayUjEZPs7UUQCznGK6utAXAgNbDbUfRO8vEEdoRElYqaRaGbrDsSHvKQxQ+8ZnJIqQqyJDvXBdxagiJFPfAo2yrTtkcY5EB9gat3a4xq2n7DE8DNqlGr7jpGhsUpXp8YOTR27yBFGyHNLHrVuQC8ZyJ56SFL1H5PXFRUQgKw5h/hrPFGMIY12f7boFubA==
    EWEKA_USERNAME: AgBnyed1PiJPLJBdrhpyYdOuWGfInY1MRmvwEqSKLGrQk5/+GD8ecqUj9FaOkkLH5C3PI6hjpqcD9pueK8uU6bjCZ+19FcivcIukFPIabN8xb+FvaFh9Yj7y7ypVwGnBgI5pIew0qbPyg3HvY4NcHeiMzPZ6U2upxSkrYLxinkMdy6OsG/gKixhlgN+9mKFoNt6YrYxVr1pSxPmAHq9uvl0J50sURQDhdmNw8EDNgVyUcQZwtun69vNKB+XFGsz5XXidlNnAg/I/x5+BDyASRTaD7I2Fy83yUxN6E2eYfL7BSZwqWR5XOBWrfe6nRnpzBUSc7TQ1BEqR5AaFA+w5UkfH612ll+VP9V/V53grrfaiCeRgl9yqd2wg5bGdknQfsonHqzXLkGrrtv43f5tL1VwlquVwT8ZKYngjXynQFLCVclUMzqg5vOY1r+yMPR+Z1DfD6C9LThxtQZ9p/vSprl0agPurIExQYEJajKIRf+EQVQydLO/MEDOfYcWkfO+ojUM9uv9tn1oHlbWyrfnvcMk4eTw8lQ1wOVLET695DTj4MCleu2lC22QtezMp8yU+iVevv2FvnRV23MtQ8oEP7yd81IAdRmKi07g9wU2F95y1CTzRfetB0kTzq0wEswScQQe5ZiQsND4Hxx3eFRDUmRk9SVkygCRnOGWMZIZxjZRBRKVa/+TBwMP/74EAm7/NMJIPE6TCLex9qPLUcYAYkNjd
    NZB_KEY: AgAn3Q8ZBdg1PDCsFygPN0V+nNktqW6e5EyKc5H4Y8oAZw+lE7soR+uOQzfYUzJYiuzyA4Y60QvSxMoLc0tbWUtD4avSjZi7Xm02F5lEn+AJedHzZnJk9XJ+6IUhKGVX/q6PrKHr/dL1n6k0LJ1HevZkx5mwFghO6Qiel8OjaWFiPnYd2o1CYYY+g2cROU0LIw/t/POX6g0Xatd8PQHZ8+bEOoGa57DPcbvqZQTlAiR1iiG6buxydsSdDayLTHvbN06mugMEGUeRTGhyW76vBRe5ABnXu24Au+Yh1zsqB0oq6Q33P0H4xKKvOXWCGCx3OqZ6f9vMRvVJjIKhgKokV+UgQ2jZ2TzhEZX+TX+8ooO+zVyyQ4psiiwogWVF3jYB2Cm9eJLtwuyM0Uklb0RO9IIAkEAMDlZijYrJtbuPh+LsZJHIeB7f7ZmJH/2YlSC0Bkms/Dc8EH6M2XelXH2vJ1eCGryNIYIEUDUZUziGoy7xvkptlhl1hN5kx7qy2RVtTvk9rePyoWWa4B8qYESTIr2aVyC/sxeBAlQc0OXtPX/VslxGa7CpPNXGctIK+nTvwDhdnyMEANsJXIDIPKDJ0AVEu2XSM+Muj+j/VreY3ABTcVE7lWO4jUMT1+Ft1lMY6nDypHiT6SSf1yYPh3NMikJ7DXUiHJM3AZOXcQpDOw1eT6qzwEw4+RONYnnyixmlnju4Ox9DF09S6x3oWdOLOeVeOacFRIxQ+EF6mR4+ygd/kQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: sabnzbd-config-secret
      namespace: download
    type: Opaque
    data:
      sabnzbd.ini: |
        [misc]
        port = 8090
        api_key = {{ toJson .API_KEY }}
        nzb_key = {{ toJson .NZB_KEY }}
        download_dir = /downloads/incomplete
        complete_dir = /downloads/complete
        host_whitelist = sabnzbd.download,usenet.lab.schaermu.ch
        check_new_rel = 0
        auto_browser = 0
        [servers]
        [[news.eweka.nl]]
        name = news.eweka.nl
        displayname = news.eweka.nl
        host = news.eweka.nl
        port = 563
        timeout = 60
        username = {{ toJson .EWEKA_USERNAME }}
        password = {{ toJson .EWEKA_PASSWORD }}
        connections = 50
        ssl = 1
        enable = 1
        [categories]
        [[music]]
        name = music
        dir = music
        [[movies]]
        name = movies
        dir = movies
        [[tv]]
        name = tv
        dir = tv


