---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: gluetun-config
  namespace: download
spec:
  encryptedData:
    GSP_GTN_API_KEY: AgA9onqGWWj9nnrsZk3CJvnZMHmZl7pop0/LyxWs0Z1aJ36Jrqm3y/eJmwm8et3LiHt1WvUVFIUv3rLSrr/nfDnjIZrpdD9zQT5rOMIyrokb/5lBCu9+xFsdZz1mbki941HS+AW/21Wq5B2/Pc44Q9pjv/pj0zfS9bhocT0P/DXE/+Kaw5d5GMAbavq1KRiZ7PkUNBC84ViHWy8PEjT4H62G2OkIikXcYh8T2A6kMayHe6dKsWvDsZ+ip7LGlHJ1bzuac7EakFypvwDmFBDfaQ3tmh8YqhwLnBIZErzEBPaWfNigsJL0sfolrvp9whL8To9Qz/OWU1T2HifKnLM4k6mOADP19t+Kjed46cRJYOusu5khcIi/88aIVwF82d/sltCoEghJw8/BPttaw8tyyYocjVGOw/nSyC5zBjbHhcBu78aUFEfMRm4cLBqeRYT+7MOqrLOuyL7YTgOgWnwkI9LBN22EXAjpKgRO75x12fxNWS/f7ZXsTadBAXvItD7GWYWPHGa/BdP+UpcJBN/Hm4saFwXVbugsdl/B434l/lJziB0dPkcj4HPCmRCFMs5xuBaa4gKzhktU8PTxztF7K4Qvh/HFfd0SCaks+/mF2mp8FuW7pd4FujjLCQ9h3FWjDL+0aWjASQfMMgiIshI5a0srYwNePqxRmxbn09IKLlsBtpriLOGx+TWE+XYetFZPzJjIwm+PKmcmQQXKWP5FDSLr7Mg/YmCmu+zm8WU1z+FFBd7OS9TTBh1tbO9kTT0swd6YtIDD6iSWP1QtPLLNA1r3CW7wpg==
    GSP_QBT_PASSWORD: AgA6L8ZNM4r2nuvvIhNnDersW42/arXDg2xNjd4pi100bwA9nQWAXs9hbQXyVlXyygGURZhwbPhyXHlaNDZzOEZ2xHIHMcE8BQCj2dMa5Q+3YZwsSovdvWOvlPTHGHgKOx22h0+tEpWa10QJcn8DGAQRysyMGOK7B3z25yIdATuqLGjQVIjE2dKcACvN/1RzIQPmYoTL25bbd+qTl8f6HLKGtI2ZOnr0cma77NVcQsYP3szuTz+vCLHuKR7IlNr1ANNJFYcCgmvNR/4zI3g++vJkHN550UbPu2tw+wDz/8nr7/Hyj70Fi2voTL1CyJTplxyOUQW4T8CcD60rufLVafnbkyOlRdew/FAjhRSgkOIAphM3iq6lpf7Wc3kaE+bFVDYf/+NHlcl12l4FDSeWaHnC4MkHyAb2CK3Wq/kexxRQd8WNjQh58yY7k1SMJ6HOKeOPAVcbv+IR6GPh582CWNH9fipFNygCqyxFGgkkK/BmIE4atfqTdiEj6eIQrVGLdtSumC4xQI571BfL4g++YB9LnRO4IUX+K8Gg/3LJK57UMBWQ2Wz2fwvG0pU0WHJ3+o3mRaEtF9DCNKDEhOqSbB17fTQTUl4SNFNu1odMq1d67KwiDCGUhgCxH5vsy3pnORUuxrjHw7r6BQAvqKz4foAmVnVIDId1tCLWcd/2N7shmpVc1k2ABJb34ErEfIb8xhYU+5YWpc4AgYWFXBUp
    WIREGUARD_PRIVATE_KEY: AgB9KfN/Pwf0MmrcW3wBBAAZO/tVZ9dJOiNQbWr30HCK/+CteNjkLydx04GC870S8H3feM5fRpCj1JCKIAsp5rmeLW6J6JDKppGc83HQVxHgbyRGsKKe/S8zgd6ZM9NZhi+iI4YAkcEy6t9Ib9X/nqMxAPzuq7dr1sEU8RYsOYC22srr21jMk8wcJ8/avGQUIkfH/9oJ3gSrkOcmD2oT+5USd97F8CxamP3OdJfd/6tcWatIq0xI5JSHx35v4rJcu/wt+2E7bCLZn1ZWPD4c3xs9bv/Hos/noKP9p3wJX413HnBlCJ8b47X1/QBlP+crzGqrxPYHY3Qgajo5HA3/N194+04JViP/Ir/d6TxIEIbXpt6jYTLGB2zm/zSYY91copMwqogmONz8sv1OG9lZMoGSk+4eC09Md18MpxlJU3hH0P/Vdhkq6Voa68oRz5A2yQNfUxbNCldgbYC/CHCbo+txwkuhZbaEoGQTEwmcpHAUnoqL7JJzwfmtM/Mga6Up7x2mNyDZ5kvve63d7b1Upt1p6Da3oN4+0GMouRofXyQG7TLYIDOiCVritqtR3vCLGNfIBvlJJzEiEIr8CMTsWTojioZwQvAAoq1lzGdKZcuR4EIeZZ5E+TaK/K6ZhyYfYJ8UuCvOKntBaZStIlP3YQViX9g0U1xW6PPn16x12Ia/ZuHJ8etoJDzOPbhwQwF6i2r4P8Nk1qY0i5zIXPtIEyg0PGszXnUTIg4YgcUkwyN3Cg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: gluetun-config
      namespace: download
    type: Opaque
    data:
      GSP_GTN_API_KEY: {{ .GSP_GTN_API_KEY }}
      GSP_QBT_PASSWORD: {{ .GSP_QBT_PASSWORD }}
      WIREGUARD_PRIVATE_KEY: {{ .WIREGUARD_PRIVATE_KEY }}
      gluetun.toml: |
        [[roles]]
        name = "t-anc/GSP-Qbittorent-Gluetun-sync-port-mod"
        routes = ["GET /v1/portforwarded"]
        auth = "apikey"
        apikey = {{ toJson .GSP_GTN_API_KEY }}
