---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: gluetun-config
  namespace: download
spec:
  encryptedData:
    GSP_GTN_API_KEY: AgBFUgSgv0UhmCpA+RhgOcs98QTuD6q2QYL+ZWzjfYEp3gnp+syJlMpWcF61+duTt/I6CntUGzsM6YgJJf1xhfg6jqmOpwc9OPpeyEgWy7MOOkjS3lH1pCGFCiKij9EO5HGiPumtWYvdEx/javvu/knJemvtbMSNJU++3o4lygQAffGdNKq/o5KDTsdlRYri5yRoabPVVIoaeGKm+HVHJhpjMkftjfPZofUDTHIox256XIc3AFf+wOk7EE4B6nBi4bRnt4TFppgMHBDlQWcyoseJx++27USZGD3NB1fV34B6Y5ebwTxWKRSmJkHTODut7ygUZpkI+tKNnh9PkxidbLszhkZ8MtJdK907T/B9P5SWm6jiHFxfPQSLhogG6uBeAtYYdLjK2PcCZ9+e72sOJffECrJVJGSvjiCiIvgGxj3MZXYWCQzvM+sOkMY/KnyBHLjkF3idYW+I+LpcKs7QmlbdXhNYsPARB+qAF7ZfIkzTFefzYaMqJ94paJdTTs16VLljetwxHXGNLV/92A3sGf1mFo5oSn0Or/HczRajuiGN/C34B5yXoAMu/PxLFRRgcU3MFIvmXmefgx7V6QMGApJkHB147XmW7QX+taVWghHgu/JCNPEq+8k6vDrxyNAXDrLYch0ANmlMIuNGjYVr8Oj9xNcEG5h62GzTGHNqXlaSmyiPbXRY57oPmps/N8cX4wHPu2E2iVDe0Wpld73upYxfn7TU4WzUzxXPOmvtEcJHwOdf1ZlP7rDXtG0vJyamgcOHtY2G3PPE/XwxB2y2/IgTbFDphg==
    GSP_QBT_PASSWORD: AgAGj4DeXXgaWHdEu1n/lFVTAELQax8BLgHszUJZ4teM0fy6eL0VxmEf+/w3U59Z9yujTv2VImjfDIYjOWt2fXALdUVsBfmBAMPz/wI1dG8qG/5HmWSZGJ9abHeTO+BD3CNiaHAp8RT/jBTjIRk8gts4gA6c9eh1iqSPBfqaYDn5aVFjs+tktg8qxbCQVlvo2KP6xEnc8cp4dQRBWaWZCakjIMRwupr8Uw1knJ2hcKBZp0eMhFcqeQIoTLPCaEGFaCi0BqjGWhNjEAMjav7uTUEWQAIZTDvdVHymY+YP5v+6fdVIDrP8L0hZsqTVsXeCasJoj9vjRz791DtW/a1XPEcgSA7J38V1NB7P9ER5HEzIr2wXOirbqZ7FnPIH4seg+xU3nmZ8GpOHaTlYJICSVra0aB2dX+LUAR9Y3hefvT1yTrSVZyNgEc8tdoBPJiK7kvGKFYEpBO6kXAN+BzPYtbY7B3TPVL13tz/CQazwB90ZmiMm3rpnzDBMRctOqjta6PtEdBCOnhiaaPo/kuQBxKK8kVUFP7btmNtVTHcCDCM9Lwhq+CPgAHigt9js7k/pHjLMwhirJm7Z60yI2aMkp5+UnUK+dpZBsSN2g86naqqxqKHklM7EsyFRGCU4pUG1ezkcSu2x2cel1H41M4bcrPTrI3/tan+uDPRoukJD0+MYFEEf8/woDBZX+4KrkwQudVvvHl4AB0/xJPCp
    WIREGUARD_PRIVATE_KEY: AgAOIBFg+SxrtvPVPBeu5/nFNRzC3mfbwwzqB3UKT8lvEjreNXRYcm1BKrEoZHye7lpiSX7qM6zTqQmm2daobigeJjv7mw0h7JnbjyJMcShFDKQKkrdtpkmg5mNyPDAIL1EaKCRQ1ivGLwhRpetykrXZckTDWeh7dg7RRHLEjdKZhjBXn+h3FmOtgMIeWMGEz3EwZ3IlqLrqC4ofk8roJ8QVBrfDCxkltl77n1zuy8YOtIcjcQscl3aXEDIAf6M6OIc4O7Pc9XKBb5XX755WmKxg8yuw2cvWL7RTrLvHC8vpehx1GkEbFqdX9W2m5jNgVw5VLw5fF0VCrKOCsuQIaj3MA/cigL0n0V03Oi2YPSlW3FVE1hegX5McwktdRF4zKhYme6R1duhwY5y2Z0wHNm7XQELPYcFfqvIVgeNTX/mGtsbLyUD5KRTtgyhv2oe5nERaKtOSU6BT298XsGxuyBd30Bv8z0zbEXea/zp8e4IZ96hpAQeEDvFULC+wYltr/l5EDqDRJJ2pqGtDzWJQVcPSvxNbZp1mgak2vc5jUQqObbUJuDAtBODqnQNoldlNNRTt/bfF8hMPRpE2p7Vr8rrvNi3DmdouLmjoTYDdSR/W/MNwtWYKsa1jf3+6B07Ud7mNng46RnPqMgZE7sZOFQZOS84eUssZGdBpZ36kVOwG70ERfy7PCMkafu8ksFL77mwirjq/akWNJ0Jitz4Bmmn+fBzmvSiDFA3Wlsa3E56zWRdzxbWfX/x6erM/tQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: gluetun-config
      namespace: download
    type: Opaque
    data:
      gluetun.toml: |
        [[roles]]
        name = "t-anc/GSP-Qbittorent-Gluetun-sync-port-mod"
        routes = ["GET /v1/portforward"]
        auth = "apikey"
        apikey = {{ toJson .GSP_GTN_API_KEY }}

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: sabnzbd-config-secret
  namespace: download
spec:
  encryptedData:
    API_KEY: AgBJQKICw10NGqgKg9995uGQSEldDMfSqCOtmGgwa0atsrNQPxS5Avfv4M6aQk63uPWn0wMHIGEdW6aSpQfZ+GOoAHmKRsiZvIzeQCpZzGnffCxchms2oEdwJ15RBg2XsaYw7Al3QhVg/R2DxI5x25VaKa0xnIzwyP/+xADTUvni820b39Ce4Ew/yClqPaDOZGx50ia1il6E0TJzgM9QiQunQm3oC59nzuA3L5/lNLxUArPvF3Hh0iGg/hHP536qSZfJI3P6L3YopWZch1vn+aFQgLUg9dsvHkgOzgpxfGUJYL4gI6Q536TsE/MPGULnI7cBO5SWJSI0CcmXnIpVnJgBSN6/CbUGKnVac9eAVn3buVD4P5D0OWT5s7Pmog+RfAKh7YLqMKmVmReZUbr3nzA9FvFWbrFzebyI3Za+hJ4/gMOGJiprGUzzcvsEvXODoAT5izj74gYHWp5SdP/iFoA4TF2fQT4he3a4D7yuGxogcBsPSAZ8KEnvG+idEmVWr70ZJ5tuLaYwsmhIQQSk3uNwUySJR9CvX4Rtk/lyNeFFMPFSVQk3buWbR2ru0XoaVUmV6yE4RypwHJd/eXHC10qM7AuSpJOObKFtTfRAZK9SPpO24h6C4VLejSIMkfP9dUoxnsnRGX6UztQtA01KfK92W+6ydVJwRQ00o/UD1ovg4NHa8YYV9dY94ggOsjO2FbH/HJ6P9dydglNPmUC/DlfMA94qn5RxykXk6GUBw/wcIA==
    EWEKA_PASSWORD: AgB/21cao2EhFESta5EAZyXeB5kj9kRMMqrHJKTVs6z9Rmmh7juipGiF94PdV0QJ9jiuXD0N2Bohvgm5JKbtbhUISbF3UzHMd6D2PCAPBbg/mIGL42f28aec3vy4XWDozLfQiW679ccxXi3AiO0HgZcT/jJQ+zSnjmW4dV/VjkmIMZuF9PG8LYfXQUyjZIasFUsHzg+3fMfNDGatFCbrBWTdQwGFlEdUcOSgiis2BSJ748Yl+/PXCjrCJWoE/6kL9RGR4SxjPL67IJN5dH1H/+uRagmIngjOENbkdmbmBZ33MGY359hNm/IH5sgYA7gbMasBDryCjBtCR8aCOrO9ad/6QEL89bNZy6Jls/vmZAZWFb26aMLmmVhRYYwwY4Xvx9Gt9l4ryVWF8pHOBj5cV7ExECOM2H75sLJbMiwhz+StloFffp5q9s4oR0beW4Mp3cjzcHMQvd47I2pwhstiHkXdFtNLbDMb0Ewba17wo0AbbR+xTIjMMt+/x036Fi/y5MHVOS7qXmCwBUHZreqK9Q3Y9wphFb4AyG8quU67qpuqtBZsRgmsvEFSlJb4QfNm3A6sFZ9YJDfYxDx1dZMnySK8525mSFML5Ysh9mU68x4Z3uV8Hz9/xZ+OAvdoGPBbZwR7U9wo4n1mwou7BI2e4LZor3RYYktVSxMFBfd1kl13TZP0ZDLIoTuL8OANK8C2bPNkAOHP2z6nlvjCnft2Iw==
    EWEKA_USERNAME: AgAL7C1tIv+n49y40NeaVltgRPjjLRTlLVfbKPzPLPTU2sIKGi0BeYmMp90O0vuSt7rFZKfOqc5YdXxIIOy6rgHWn0RQniNriN9NFiFCHDoLzHah6JWrIIHgDPXh4lMUfTn1/JVHyPvHYGxAY3rH6As7h5+eHfBS0G+6Ju772xFC3n+znuVXVYl4MSIC9M8dKy4O31OPRK7x7x9lrRri1LagWJN8GcNx5L/js6MWZnpAaaIIzPBKguASSOhYNAU+dmAJ2SNYwQ01CZUascSOPY5ClEPZuy9hcrT3XvYQyWUTljfWZaPCSW+nNSNzkpFwZKIZ/9VF1ZA3esH9OgkZi2fcqAyZ3tgxvI/xvhWlH7ROvIl0zZdD8Dp5pFWE77KYw5WTvSE86zX/y1BL+puZFDfMAskC0TBijCns/rCDnOGv0Nqy7SDpLwgsbWUT+2X11lGsy2fOE3hub6XtRw0Bq2sjfzzyoCXv6LXjXSzt8RfJ3mzstSZAeeNk6Me12tuV9w7Es0YUuu5qGYr8V3uro5upvZ26P0TLHZsfetlkNpppjBZ1ngIq6dLIkoMOlVpqdxzq9T9Sy/mzRSpurNeTXRAVuSJQZGyUqSyzwAdUg4OYY/Wnyc/ptQ3+mQwtANzdo/jG8uZ84mHCEsDQtEmERPtoZ6LUdfUkMT8/qadxiALGtPtimj7RSeK6OfUsLeFCjk4bHF/P7nI1kz66OUwyLAh7
    NZB_KEY: AgBn0aCCvR8IAB89jlOYRxDM8bfe9Ivj4JNIr2xUABM3MdjxiNGsBKVfTqchd1/WVhXRm9EggoJ8M9ZOHkHH7aL8x/r+UA9QOzPqSI6GvDHY00rzF/6HMUiur1OUN83mEaCY4z5YNSmXBjboJ6uu/Jk9kkCoG5jFvR66clPnmOOE5tKubtyZ6YxxNtZuWYI+i1LSIZ7jflTblAPGaw26MSB+VwREilyV14pYmmrBb3B68CVrpL4Ijj1XlcJLhuCA4nbuuOLFClksQXQLMv78Mrk8jB+MsXFTL+EbugPK8MGsNJMOVzP0Id8m87fjsXD60qcz+OJYUDuNK57dLP78H6VdCQ0wdvfY8qtYo9eTpadFfEyG/CV5cnuz1o/jFDxrdXnOg+BnzVu5wDTUKMgne9faj5ECKKb1zrSA3F1N+acYzJVLSnFdSHk50un9UHYeSKcj4JkvtvI0R3Z3Jszdw+N+2pJ5nnRrwpd162KZrA/ubC7UQVp/+1/zIMwdOhghWbKJUk5RZDRM+3GxyVdnbFqSX3b1sh7uvfx2chlEAlOzoynOBJRqKS+H/YQzCRm5nxB1TToRr0qpdu4Rk5HlREk0kB0zrKr8JRu41RHUgju5Nlti5uXuf3+1smYQRVfcfwqWqSFGTSplvxNDWx8lbQrkP6O1WE5Q0yDEvlzRDNXW6eZVofplRpdLjzAF9R9w3NUWxPTVHDORHy40fXKs+jZQbKV/g3kDrAN1b/ucn8eO2A==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: sabnzbd-config-secret
      namespace: download
    type: Opaque
    data:
      sabnzbd.ini: |
        [misc]
        port = 8090
        api_key = {{ toJson .API_KEY }}
        nzb_key = {{ toJson .NZB_KEY }}
        download_dir = /downloads/incomplete
        complete_dir = /downloads/complete
        host_whitelist = sabnzbd.download,usenet.lab.schaermu.ch
        [servers]
        [[news.eweka.nl]]
        name = news.eweka.nl
        displayname = news.eweka.nl
        host = news.eweka.nl
        port = 563
        timeout = 60
        username = {{ toJson .EWEKA_USERNAME }}
        password = {{ toJson .EWEKA_PASSWORD }}
        connections = 50
        ssl = 1
        enable = 1
        [categories]
        [[music]]
        name = music
        dir = music
        [[movies]]
        name = movies
        dir = movies
        [[tv]]
        name = tv
        dir = tv


