---
apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
  namespace: download
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: qbittorrent

---
apiVersion: v1
kind: Service
metadata:
  name: sabnzbd
  namespace: download
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8090
      targetPort: sabnzbd
    - name: http-api
      port: 9090
      targetPort: sabnzbd-api
