---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: download-data
  namespace: download
spec:
  storageClassName: ""
  selector:
    matchLabels:
      type: nfs-shared-storage
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 20T

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-config-pvc
  namespace: download
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sabnzbd-config-pvc
  namespace: download
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
