---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: download-data-pv
  labels:
    type: nfs-shared-storage
spec:
  capacity:
    storage: 20T
  persistentVolumeReclaimPolicy: Retain
  accessModes:
  - ReadWriteMany
  nfs:
    server: 192.168.1.244
    path: /mnt/MAIN_POOL/data/media

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: download-data
  namespace: download
spec:
  storageClassName: ""
  selector:
    matchLabels:
      type: nfs-shared-storage
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 20T

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-config-pvc
  namespace: download
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sabnzbd-config-pvc
  namespace: download
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lsio-modcache-pvc
  namespace: download
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
