---
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: cloudflare-r2-store
  namespace: pocket-id
spec:
  retentionPolicy: 10d
  configuration:
    destinationPath: s3://schaermu-k8s-backups/cloudnative-pg
    endpointURL: https://59469c6e9b7a0c72d7efceab1b0152b5.r2.cloudflarestorage.com
    s3Credentials:
      accessKeyId:
        name: pocket-id-db-r2-backups
        key: AWS_ACCESS_KEY_ID
      secretAccessKey:
        name: pocket-id-db-r2-backups
        key: AWS_SECRET_ACCESS_KEY
    wal:
      compression: gzip
      encryption: ""
    data:
      compression: gzip
      encryption: ""
