---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pocket-id-db
  namespace: pocket-id
spec:
  instances: 1
  imagePullPolicy: Always
  plugins:
  - name: barman-cloud.cloudnative-pg.io
    isWALArchiver: true
    parameters:
      barmanObjectName: cloudflare-r2-store
  storage:
    size: 1Gi
