---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pocket-id-db
  namespace: pocket-id
spec:
  instances: 1
  imagePullPolicy: Always
  plugins:
  - name: barman-cloud.cloudnative-pg.io
    isWALArchiver: true
    parameters:
      barmanObjectName: cloudflare-r2-store
      serverName: pocket-id-db
  storage:
    size: 1Gi

---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: pocket-id-db-backup
  namespace: pocket-id
spec:
  cluster:
    name: pocket-id-db
  schedule: "0 0 3 * * *" # every day at 3:00 AM
  backupOwnerReference: self
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
    parameters:
      barmanObjectName: cloudflare-r2-store
      serverName: pocket-id-db
