---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pocket-id
  namespace: pocket-id
  labels:
    app.kubernetes.io/name: pocket-id
    app.kubernetes.io/instance: pocket-id
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: pocket-id
      app.kubernetes.io/instance: pocket-id
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pocket-id
        app.kubernetes.io/instance: pocket-id
    spec:
      serviceAccountName: pocket-id
      volumes:
        - name: pocket-id-data
          persistentVolumeClaim:
            claimName: pocket-id-data
      containers:
      - name: pocket-id
        image: ghcr.io/pocket-id/pocket-id:v1.16.0
        env:
          - name: APP_URL
            value: "https://auth.schaermu.ch"
          - name: ENCRYPTION_KEY
            valueFrom:
              secretKeyRef:
                name: pocket-id-encryption-key
                key: encryption-key
          - name: TRUST_PROXY
            value: "true"
          - name: DB_PROVIDER
            value: "postgres"
          - name: DB_CONNECTION_STRING
            valueFrom:
              secretKeyRef:
                name: pocket-id-db-app
                key: uri
        volumeMounts:
          - mountPath: /app/data
            name: pocket-id-data
        livenessProbe:
          exec:
            command:
              - /app/pocket-id
              - healthcheck
          initialDelaySeconds: 10
          periodSeconds: 90
