---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: pocket-id-encryption-key
  namespace: pocket-id
spec:
  encryptedData:
    encryption-key: AgBkokEJUhABVoaNNVauXusd+9hYRSTHVwHWjXIDlZyC4+eAfPhXeA/a0ACt9JFIyARyLdG9ThpSK1NwCuyuqZN0lofilgo7T5wuXJnuUCNGBPi/Wy6alBx1vntj99czcS68Epkt7e5tpRvs3DUUasbvv2SCc9Stb+aMF9e1QUhQsvtR8Eqauv+feXPV4sUlMz1ogOSS4BHbRxfzByt3UGTRT7LyWKlpXgMdWAxzs66zYNNCjj1+vXrLQEhhJBpEdgx3zDsVP7iEcKCYkkqNWg9xsxuAgh8DOWGDHpK/JoCHsbh1V8vkicoFgslRqTml2le/A09+BQrUyTvihl8J6msQmUmJonGeQTYymI/SZ6h4CNefIwBV1S7To7CkKCirBflhrytKAWgWxdQLKYxbcFiFil40ChfG5qE6RmpYFonybIezeLEP9JioimlkKcjgy9ZGoqxUbc8F9SMCknISxAI2kpnZhKWGO+cb9U83u/yNYGZlf0cpXJ8r9pyFIDwT1eJEV9okKp/78p+JE0FJW6geTUDnqdVIpBcmuadWwYtEA78fCB3MXIB9RstA71qZTBxHm6XHhChiEKGpdONMP1hrYkb/SR3nm2R5tEoGzuHGHygA+i4Ao/sMB5+W0QNuI3kFW908DZFoUxgWSMD/+ZMPECEBB92diDwMmLbjZ9aMa1dx60XeFFtBZVKLfJJFBIVQb8QmLzqsc+3YsS3p57pnvukXoCLKCRs6UTqMkIP9+oB68LQ/iZnmCEMNZA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: pocket-id-encryption-key
      namespace: pocket-id
    type: Opaque
