# gateway/certificate.yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-lab-schaermu
  namespace: gateway
spec:
  secretName: cert-lab-schaermu
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: cloudflare-cluster-issuer
  commonName: "*.lab.schaermu.ch"
  dnsNames:
    - "*.lab.schaermu.ch"
    - "lab.schaermu.ch"
