---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-dns-credentials
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBoiTlx3XFm/QOk9mTJxC31ztaph6e0zHnl8+meETmvzset5J+mXUou6+qkbgiB4XkeW2c/xUl7Traah5TVkSgf3VYDeEpsg0qG5TRLvsO2bvLPipXEaotK+dvTm/liIqbaj9fglkFZalgA3aHcmvqDQFbkiafWDWuOwaj6P6NcY4PI18GDyV1CDXPbJqOFm4n6RGxL0ZvtyupEimcpnuGVrpUfxnv6aH/2OBfrzt9IEZWss6zI8+jpT9dQICiKSXAUO1cPqsn9JPCrCVTYAeLbt6NR/9pGdNcdQCpKM11OD509kh/ujoYhIlRth7T4WDa3UjJM9MpHsCFGAtYatzmUs/hA7FArZ3YHlfSOKBIYo9izsN980Dk+NuEVvYd8pfdgy5ny8280nHT6pQtCnWnRSnAUFp8d+Fp7tJAMtFp4sl2NXcxjpz39YNnTlbDq6cdQkixQK07McOb3cU92kgKInGDlmiEReUsVvR5yVvVAocOYv1oAYbIAZLap/hsZtHQk1ZGVXshlDP03QDLTpcv+zWfh1gy5NBiGkjjl47gJQeX0yWB6VxPYmA/W4sRVAnIjbfK+4wao2zdyBicMTFND9arf4LOI8t2Oywle4jAEjVDmm0BDaFJkBEGwc9Eahfx9zXcdKbAvWhcBhvG+9ZA8d5DLT7CXQ5crojg2/sTHD6cPRl3Hoj6cjBGCdksKFePBsL2pqxjsDOpaXoHYsvx4CJc+ARFh6O+UZemCFtj1oiiVL+Ag/pgx
  template:
    metadata:
      name: cloudflare-dns-credentials
      namespace: cert-manager
    type: Opaque
