---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-dns-credentials
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBnG/b38D1iQRD6lhWAzDOHK+bjnBeiiTtXz44VrclBfLGKLf+Kl+t/Dx6pJHVm37l/dxCoYEyWK74wmvSU4/1CUpg3aJkflD9ZC5f14k3t6idht7r8rqfiz8auPYAmLVReCzwsAK3NuqOsjg5sWAUIYkjevOMFXyFTyKTO3Xn8bQ/2+lhzArfDhF3iu466brBhn3yqiMyymau2IetafjC8eoHWdg5GZTSQgeCAF/RfpnR5xNG4fzVV6ig3Pdu3cTzsl9/RlxjJQp3TySVfw7te5Dpb51XcrroT9SFs39Gw8iZo2S3NLp5HLmVFfU7Sbc1WeRj84r9EDMNb6il/VXDhIXN95jqt2bGXGHJzW5f2EBklzPa0iK8lsjou/Xxf4Yo356Biim8nvlvNYElsQY2iTbsxLHzySMLWkug4PEo7R9PZmeYuOmuZs3Ljbywzrg/D3wF3dMWr7BY+5bdIC3rXQRhQS/S0v5gjhDMgf/jxw5NXhXfc3ogjmmOj6Ay6ozW11z0NdglaJ12rLRQk5KFcm9N40sWWXlj5ovxKVn3XWPgZd7UtsloCD8rOT7S78V+ygKmGNWvIXZEV5GoMOvcOBBG9YDtTnGgDWCKhu+nfE4VNgzZuYHss+kKY/H7Okhzb+lQrYVc80IA93/fioNSHAxSyN2zZUXuSpw8ebyBoBeOUXeDY3WUHblXykSQWJ2jxYkxtbNhD6cy78n8EOxZBUxQQ3RFQdWSNfHT0L6LMP9qK1X5tRofm
  template:
    metadata:
      name: cloudflare-dns-credentials
      namespace: cert-manager
    type: Opaque

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-tunnel-token
  namespace: gateway
spec:
  encryptedData:
    tunnel-token: AgCHrHmvjG1AiihwFNJO1ff7JN+4SsnCk3trgcq7YCDntSH431uw9sWZ/XW3OKvPmKffIzOR0MWQ5c7q1faF0TGB4Msv3xZRw/h6XeiHxAuAnn9XEqkIPRk1j2BbT+tHmA8BGlWDnJMseqiDXUKSuDU2AFIc4NptooOPwVf7sOVh5VSodB8roAQQ1JrSZ2DepKOIFK5I9+7P6hNvXT9HmIHxPvYh5wBgIttqYPu+onBKdUmgpyD9ehr4m9gtxl4MuVlSeHnuyilhgBcXcqw9ShBNKCsZpBpK3wGNQEmHG104JewQXKm8mn7WMkObX0LT6xkta5pkLyGWNO8M0juilBNnEW08/tTmSMJjz65KLs8H848UPW1Bhqa+XpKcxA4crGXc78vXpyskYUFauDcvjlIs4yd0TwqHT1gM29HhlzFEQ60xJ91ywb5LV3fM0cTcW36cMWljX5TUcnvPdKPkPdBBqYb/trivu08ZJ7EzplXGEfmJOODR066qmfD7XH6KyAYZEj7ow03kx5W2DKUNFZlcKre+a+tmgRQcYIRYnk/abjAbXHH5fWEF76kljx5EzzA3mF2ypSzgnmVGidF+ui4nzcm22eUAU8u01rU614hjEd2hJk2UT/BfpjO48Kz826WOXHXUj0LCU/8HXzmBk+wjhiMr40AFhXoNQ1nf1dPjFRqUZ37wbEsJgFomgl1uNUMjFYrEmOCmYNFkAOTdKaHXqM0UW3ag7VWvttwVzvU+poyWBGBalm9+sIa8JJzKryZVspeTd6V1YZVaBw/DxwK9hnal1k+3ppAh3aI4+LY0sB0kwZah75TRJiBC4oK3LrHV39Yntvo6+PChcMX8Ni4lsANQif2q9GD0HinUlJ9imt4FyurQ2TuogYqev5hfd90IPJn6AzfFu73ZcZVhDVeXi6dxVNn/J8KGEj3Te9cxzQjdiIc5M9IY
  template:
    metadata:
      name: cloudflare-tunnel-token
      namespace: gateway
    type: Opaque

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-tunnel-credentials
  namespace: gateway
spec:
  encryptedData:
    api-token: AgBBcMfnqMht+GH+siBENT8KAA5SAzAKHfmEV12pWqy4K4tQhzsff1R3zdhkYrUf9Ki82v4yxmwl/Dibd6GAQHTcYUU72ufXakHATXdincI1RPz7XR64oPnIr70WLAweRlTTWbggRUAiOQFzauOQMLInB0CpO21zcjmPslTy4vuuh70Vl71cyBJSdKj1nOvjNUtbZ0lD+l8gWaGqyIp25GfwYugfDn18i/6K+EiBn4m/OJVouk+L8pg/U78XqIYLiGCcIgHIgu+ggqH5mYF/qh6O7jC3bYi1JUOcFo2p7+ydbrdooJk8Q7LdqHyU0Vc17XIhVs3YoW05aXGJDHhvKQt4rdCE4oLCXqaY3dDxD6L3EiQi1uGv2PWlnOzKeHCebZKC/M7a0MPfUWZNEQBKQ8aCJsLsbD5cAvORl6JclMuteSyO4QT7+X16MRWbiAaGmfFAmkVTcRueyU2FsZld9/Ihyd9ye5TbBZwXHgcv6RYsX8t041klIP7owNgPYr934x9DsFHQhMvnm/y8zRonSfyuIqjPehUHStohl8piFWHCKQryufck4vDkYUyLbGPZXGnabd6Ap0e91IebTADg1Wj5ldmQHds4Ft8GArwY2ChYSW9EKfGU2XCKEwwpnXrFKLDdo1OwqL8FvR4G9vj5rEqPp83rU8mjeq1Umng45+XC0hUKU2xigwF3UwxgNLgexoEaffP7dm5sn4CYXaVBdKbs3Vbarz0duuYCn7xL5Xk8bx6hYB653Lyf
  template:
    metadata:
      name: cloudflare-tunnel-credentials
      namespace: gateway
    type: Opaque
