---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vaultwarden-config
  namespace: vaultwarden
data:
  DOMAIN: "https://vault.schaermu.ch"
  WEBSOCKET_ENABLED: "true"
  SIGNUPS_ALLOWED: "false"
  INVITATIONS_ALLOWED: "false"
