---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: vaultwarden-db
  namespace: vaultwarden
spec:
  instances: 3
  imagePullPolicy: Always
  primaryUpdateStrategy: unsupervised
  plugins:
  - name: barman-cloud.cloudnative-pg.io
    isWALArchiver: true
    parameters:
      barmanObjectName: cloudflare-r2-store
      serverName: vaultwarden-db
  storage:
    storageClass: longhorn-db-volumes
    size: 5Gi
  walStorage:
    storageClass: longhorn-db-volumes
    size: 2Gi
  nodeMaintenanceWindow:
    reusePVC: false # rebuild from other replica instead

---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: vaultwarden-db-backup
  namespace: vaultwarden
spec:
  cluster:
    name: vaultwarden-db
  schedule: "0 0 3 * * *" # every day at 3:00 AM
  backupOwnerReference: self
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
    parameters:
      barmanObjectName: cloudflare-r2-store
      serverName: pocket-id-db
