defaultSettings:
  backupCompressionMethod: lz4 # tradeoff between bandwidth and cpu usage
  defaultReplicaCount: 1
  defaultDataLocality: best-effort
  nodeDownPodDeletionPolicy: delete-both-statefulset-and-deployment-pod
  storageReservedPercentageForDefaultDisk: 1
  defaultDataPath: /var/mnt/longhorn

defaultBackupStore:
  backupTarget: ""
  #backupTargetCredentialSecret: longhorn-truenas-cifs-credentials

persistence:
  defaultClassReplicaCount: 1
  defaultDataLocality: best-effort

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  host: longhorn.lab.schaermu.ch
  tls: true
