---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    cloudflare-dns-api-token: AgCD5vLzCvHfkMJm2E9u9Um19VKSRhZV1LvD1m+uLzznLMKky5uSIn7PRfL2ycoJgEB0KzjonTEqn2TVG8SNxgVKo5tk1Fh+X/XzkKJUci72Ij5AdxckYRsPUu3OIsbWfFzZ8/EyoKQooGH/Tcbb5XqSJjHEWrA0eDIf2yrtMR5pDLAk4RRyPkdzNNUtvG9drG1ipXOVJMufWtW88pPfTaPIpZmXYAqhty8sQ2L7acrFsZO4M6Bf9Cg+YINyhsAelmOz9IHoEqdEDpWJr5XxeUo4omrKC2Yk5jrigfkcvTh+xl5W/bqa0+K77Egi4JoePSmxw9qSH5ncs4eBp3DwGBBHwCv2ZHeNvcPwP39rLCwY0B9N4mfzPEpqn4rodibFo810hnQhI3PUA6QgN2/B4uiVoD2VHs2DVzrtQR6K2FUfQdPOG72C8YiFMPUn0Lw5h1I93JpeByc36L/Vg9GNXN0mxHsRqeg79rSrdwNUv5REtxKaYpwBibuDr2A3+C1bK5DUCmtN9jkRNf5Ii0qJj0zRp3D+EEwDpNQTk8OLvmr0ZdQwjF7iJP1ICN2YXSTqhHhCIU2lomxUHeYPVKmgq3VmirppKO8/EbQLkwZynPudwKDypLC8+qEV/dZwGXR/03U7bjSUbKHPyK/bPkI+fyX3etwZclp4G6DwNFPO03O7hithhuojNF4OBAMp4jp6M8BzNT6mpdYIDITKtwaw7SA+mYLHbOGxThZjr1rr/Bp1Izh3+xXhBEOL
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
    type: Opaque
