---
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: minio-store
  namespace: mediamanager
spec:
  retentionPolicy: 10d
  configuration:
    destinationPath: s3://k8s-homelab-backups/cloudnative-pg
    endpointURL: http://192.168.1.244:9000
    s3Credentials:
      accessKeyId:
        name: mediamanager-minio-store
        key: AWS_ACCESS_KEY_ID
      secretAccessKey:
        name: mediamanager-minio-store
        key: AWS_SECRET_ACCESS_KEY
    wal:
      compression: gzip
    data:
      compression: gzip
