---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    token: AgBnG/b38D1iQRD6lhWAzDOHK+bjnBeiiTtXz44VrclBfLGKLf+Kl+t/Dx6pJHVm37l/dxCoYEyWK74wmvSU4/1CUpg3aJkflD9ZC5f14k3t6idht7r8rqfiz8auPYAmLVReCzwsAK3NuqOsjg5sWAUIYkjevOMFXyFTyKTO3Xn8bQ/2+lhzArfDhF3iu466brBhn3yqiMyymau2IetafjC8eoHWdg5GZTSQgeCAF/RfpnR5xNG4fzVV6ig3Pdu3cTzsl9/RlxjJQp3TySVfw7te5Dpb51XcrroT9SFs39Gw8iZo2S3NLp5HLmVFfU7Sbc1WeRj84r9EDMNb6il/VXDhIXN95jqt2bGXGHJzW5f2EBklzPa0iK8lsjou/Xxf4Yo356Biim8nvlvNYElsQY2iTbsxLHzySMLWkug4PEo7R9PZmeYuOmuZs3Ljbywzrg/D3wF3dMWr7BY+5bdIC3rXQRhQS/S0v5gjhDMgf/jxw5NXhXfc3ogjmmOj6Ay6ozW11z0NdglaJ12rLRQk5KFcm9N40sWWXlj5ovxKVn3XWPgZd7UtsloCD8rOT7S78V+ygKmGNWvIXZEV5GoMOvcOBBG9YDtTnGgDWCKhu+nfE4VNgzZuYHss+kKY/H7Okhzb+lQrYVc80IA93/fioNSHAxSyN2zZUXuSpw8ebyBoBeOUXeDY3WUHblXykSQWJ2jxYkxtbNhD6cy78n8EOxZBUxQQ3RFQdWSNfHT0L6LMP9qK1X5tRofm
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
    type: Opaque
