---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-credentials
  namespace: cert-manager
spec:
  encryptedData:
    cloudflare-dns-api-token: AgAFLiDiqY6b6sLu1Bg4TZykgF0PPRumIltkwpCy7fiYjfV6zU2cnJEEFOlv3QrvYkabyDRbMCUGBAUcZYG6LOVc1akdj/zDRT4p8N1qusrozX/vA2Yl6zu8xkR2BanAu4tTXzOMbf+fMq0MFruk9Z+pDz1zt3bk2u2ejCcrN0lnUzEz123AvsfPtMWNHEeNv/tqB7hPLbVMyFFnEi1NG4PY6d/DKtpyCqV8TQ3jl0xuMb125e348vw4EUzEvv0qoP9ziRrhIDqR8hsVUhX7hL49EGkSPtolV8i0EdMNBiPgm7A9BwSKJTX0H4f4nlD/IBVE3HLOd4V5LJzZXgE2GP/gVqGe50n8aBbsHbWH4PFPWy3l68TzKc8BNZu68BfcBbIbAYiisgbyfSY0+g5qMLCkoWlSo6wvi//bCsAkJeZYMC/ixiGM3cANtuvVwHQe2K7R3tC07n/GltnUVNFhQ6o2fifpH2hTcN3RR6Om2tvsFmih6QZ4uZL2+CC+0wYv9046cD5LMKdvDLLh4fNON5FKKnpRH29avd+px/sYb2O3vQzGENnGGBjp/b7/iuDTdpoZYODLOXjF/LbMcSbXZL25m6iF+ePezDSvFCN49iApAU9cb4XXn7LtsH/l6sfnTYnAbguQ3pYhdjJ/sK4FUqHcmBnqW4e6n+e+mGEWDJ09UPuc8C5IZ2PYV1z1kzYzfKHYOve0a7soZhMhhDuPL3Xp4hVAYMf6R5vShS/lsyTgouuh0hsoSb/u
  template:
    metadata:
      name: cloudflare-api-credentials
      namespace: cert-manager
    type: Opaque
