---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: vaultwarden-admin
  namespace: vaultwarden
spec:
  encryptedData:
    admin-token: AgB+vr4xX41RLdLaG+4IPtg3y9EkksRt/YByxYFH/iXt+kwNTyIa7MBVfYkeHEiWRQM+7IpG/Q/O9BDsmj5mmTEPSb6HIurMRq+nA/Bestl/V24yYVWgyMtU8yGCOWKKOB40qxIVdFTEFrvUmLzzNQ73WFETOBp17xHKKo36bkCySF/ZcIkM9jMVJ2ysoSkeXUrSL8/S8trFURKu9nT2lhc/o4lxTAJUF3T2m9EpmijdCcs+pfKeMrrMZvgkpFsZGcdzS0/tscZh7v2vzsxCJLJgUcEHydD/1AKDGsYKsB96WSDj/tebgZwTSUGx+X7vATS13XxJwWVNgdpV1WT8HlG5miNBiQJPTo1ECCt3PZS1lyX4BzCqynjAZXqrnvRk/e96fr/ZootN/cw7GqBtJ/CZItwi6TgOv3V0pYXDHmLaY5oEx4fIiFZ06FsRoIen+j9710etAm1M7ScFBg45ino7dE/0dmOPPlVlfIZ/nJec4hjIdyFpSSqdk0JHsWli7Ph9vO2KPM1g0/y9cx5WibS+CdySCE7QU3zQG27SjBclVYLZU4H+NuQAB3StaAQrZ/+dMjgf5HJHrLW29KCiGiY9vHooxsp7O64Eldw2RiRc5Pwo0gwDMr9gdJA0iw6F+LICM+Rzm4c184dB0it7dI7KS4VI2b8RMhVbZjozr51HqMd+87aUROC7dTTi7aUCbEJlAPvRLiOeKpIXP8OSlaEpz3753AkYsKJsdSz0cU+XfuzQxcMd+9Wo6NhzyKo58Ow2CnL3pG1VwadNm7K0arsj
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: vaultwarden-admin
      namespace: vaultwarden
    type: Opaque
