---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vaultwarden-admin
  namespace: vaultwarden
spec:
  encryptedData:
    admin-token: AgAxglBq53JaxloJK17pr2ImhJGia9TcVKYg5y8/r+GQFKmA/KncRqmxRwIrNZCRy61gmFEOtArQYggCx3k8W6woqY9/41pLi52pBKGeOYe70j5xr7j2VSUPX6CQfKsiz3cg/W0VpdJSOu8Vh554pZZJTUrpxnj5wQ6VqwxPMfmcqbdUNpudDj8z2meciKf0BbWvmlAVV8jZUGSBh2Hlnlcy+DjvVg5CLIrWLpQO0geXKu/17k+nt2f6EFUw5xCNH0bxtkqqzeBvNwJZykCYQuc7NdMpZoc/3HsvudHo3mWwzeakxSRCEwYDRuDLwd41Fd9NLKVbynxSRu1/b41og+4ggKVypT6jRljYE4Y0qTUH4Lb8b0FbFUvoRTe1BvNBWvJwNN7lqejHkZ8yMu5IEHG5pmNjSNpuBpTrfQLpFWgS8mANBJ+cLrStwJnDdiOJ6oVG+YsTH569RoyrnVTKw11Z/FX7gAEhI4TXS6KXn6qdSYMoVp2tLcijY/gSedD/nn6O/MUAgkOrOAjKI8pVdLuIMvOQbfgiDrovTfoV8C+Hc9AQ7S5l/n8LLdPEiv1D5Uenp5B8AgJERjj1JUIy35zOPz/ZZQbuB+cWijDdYtWrq0nTiW0kfFgllaoR8WFyy5yewhDJvW4W3vuPSX144r+h6DKfVfOh/n4BqlCv5tHWkl0M060ifwOCNx9S6TSCk2kBdSxO78QO3Un3jun+QLvRVktm9ucbOFF6jPtJFtn+dtvytBiSttEH/5dtueOio4I4YxqOej9p8ZKOb5sSe/pB
  template:
    metadata:
      name: vaultwarden-admin
      namespace: vaultwarden
    type: Opaque
