---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-vaultwarden-data
  namespace: vaultwarden
  labels:
    app.kubernetes.io/name: vaultwarden
    app.kubernetes.io/instance: vaultwarden
spec:
  storageClassName: proxmox-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
