---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mediamanager
  namespace: mediamanager
  labels:
    app.kubernetes.io/name: mediamanager
    app.kubernetes.io/instance: mediamanager
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: mediamanager
      app.kubernetes.io/instance: mediamanager
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mediamanager
        app.kubernetes.io/instance: mediamanager
    spec:
      serviceAccountName: mediamanager
      securityContext:
        fsGroup: 3001
      volumes:
        - name: mediamanager-data
          persistentVolumeClaim:
            claimName: media-data-pvc
        - name: mediamanager-config
          persistentVolumeClaim:
            claimName: mediamanager-config
        - name: mediamanager-images
          persistentVolumeClaim:
            claimName: mediamanager-images
        - name: mediamanager-config-file
          configMap:
            name: mediamanager-config
      containers:
      - name: mediamanager-server
        image: ghcr.io/maxdorninger/mediamanager/mediamanager:1.11.1
        envFrom:
        - secretRef:
            name: mediamanager-config-secrets
        env:
          - name: CONFIG_DIR
            value: /app/config
          - name: MEDIAMANAGER_DATABASE__HOST
            value: mediamanager-db-rw.mediamanager
          - name: MEDIAMANAGER_DATABASE__DBNAME
            valueFrom:
              secretKeyRef:
                name: mediamanager-db-app
                key: dbname
          - name: MEDIAMANAGER_DATABASE__USER
            valueFrom:
              secretKeyRef:
                name: mediamanager-db-app
                key: username
          - name: MEDIAMANAGER_DATABASE__PASSWORD
            valueFrom:
              secretKeyRef:
                name: mediamanager-db-app
                key: password
        volumeMounts:
          - mountPath: /data
            name: mediamanager-data
            subPath: media
          - mountPath: /app/config
            name: mediamanager-config
          - name: mediamanager-config-file
            mountPath: /app/config/config.toml
            subPath: config.toml
          - mountPath: /app/images
            name: mediamanager-images
