---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mediamanager
  namespace: mediamanager
  labels:
    app.kubernetes.io/name: mediamanager
    app.kubernetes.io/instance: mediamanager
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: mediamanager
      app.kubernetes.io/instance: mediamanager
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mediamanager
        app.kubernetes.io/instance: mediamanager
    spec:
      serviceAccountName: mediamanager
      containers:
      - name: mediamanager-server
        image: ghcr.io/maxdorninger/mediamanager/mediamanager:1.11.1
        envFrom:
        - secretRef:
            name: mediamanager-config-secrets
        env:
          - name: CONFIG_DIR
            value: /app/config
          - name: MEDIAMANAGER_DATABASE__HOST
            valueFrom:
              secretKeyRef:
                name: mediamanager-db-app
                key: host
          - name: MEDIAMANAGER_DATABASE__PORT
            valueFrom:
              secretKeyRef:
                name: mediamanager-db-app
                key: port
          - name: MEDIAMANAGER_DATABASE__DBNAME
            valueFrom:
              secretKeyRef:
                name: mediamanager-db-app
                key: dbname
          - name: MEDIAMANAGER_DATABASE__USER
            valueFrom:
              secretKeyRef:
                name: mediamanager-db-app
                key: username
          - name: MEDIAMANAGER_DATABASE__PASSWORD
            valueFrom:
              secretKeyRef:
                name: mediamanager-db-app
                key: password
        volumeMounts:
          - mountPath: /data
            name: mediamanager-data
          - mountPath: /app/config
            name: mediamanager-config
          - mountPath: /images
            name: mediamanager-images
      volumes:
        - name: mediamanager-data
          nfs:
            path: /mnt/MAIN_POOL/data
            server: 192.168.1.244
        - name: mediamanager-config
          persistentVolumeClaim:
            claimName: mediamanager-config
        - name: mediamanager-images
          persistentVolumeClaim:
            claimName: mediamanager-images
