---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: mediamanager-db
  namespace: mediamanager
spec:
  encryptedData:
    password: AgACRRD+zoCsctjv+yoAbBRrFvhIyWE+RrSl6RAzLGDIxBXaj2crR0l0QZz88MGICvpmbsDkS/LJ3V5fPDF09acWRByNpZNfh7OuVzBDw05/8iZpj7SV3dYTroPc5LS85Xp2gAd6RAGrsqYf2im1uW+Ef/VCQvf1Lxy48Hfe1H0C0gbu0xNOQx4oCzAIaR2OEvu/9iaNrhpIeRqgz6CtGpfQp966o6FBaBi0+QxniVnz8BLBf1viJ2hdtdZ57zPV3SeZQ/HacRQApSO6A3SwMwHbYoeEjyGsjT9XEQfJglmWGs3r77ZliEtOgZTkajtNOTLiJFl4M0moWybLbfJfjNCIi7b56hz+9gQMiQxN/6Q6aUix1imujNU3B+KqqOtHEp1bk9aykWzAOh4l72C0RON4qtn2rbw+f+uNuIVu/G7raN3huIBhjQqMgx7C+H9pKLKbZas7g4HMYw+vkYPwQbXhmNOnLaBMBPY/XJNaqN1EM9/ooUbACZJ1voSVNNlujX0RneIkznPB7gyHrgmGzEjWfIxRvsWy8EOFMyMBJTy5gmr3CC3g3YPZZngexlRM36OAo4ydJYt+5HKSKFe6k77oL968F510nsv95KHdlgGwkKm1iDgImWKIWcqRWGCGyYC8dMbS+LcD2pcaiEdct8JYFgiNa76/vNPDvm7k2cigTfVk0wEkWyzJq5hl4qY/UDmK8k4OpchQipSCMf2n
    username: AgBrtA5eZO4QE084Z8TwZPS0gcXMpZKVsopZT3ZLqBbRq/E4cUY1y6M+7ZstsuXKBReGiOQQigxFVFTo/9gxaU+hdiEnvskCrQlBrkHCvpJy4D65yv+gPDTI1OjOA7klea814IY54bkn5lk+UflVtMQroUaNzqBON5/jbmbhoSXCuOjWRlLX4cTHfrZTRYRdxIwuhRl91fHOiJovuDWZDX0LdSvovVgl5xyxOOxcYn4b6voezwRWeMpanVnOoKUu/7KnxzrZ1Di02mQbl2pqTrkgmRICrofADlj6Zfyr+X3thWqK9jIiNqR0FGsUWCbuwFRaUL3EvghcHce2ggkrpQmpV8xN+M4s1kmh6Hg9Vzpfm25zHgYqgZeV+r0IZWdK0BJ4rTgCgIRAXVxfSPb6GjcOCF0gVBRTAJLy8oPddO8Wv/W10w+Y30a4kqnpPoVCgg4e0/i+a8ZAeYKVYWnqlQSt1oqLIXxASrTdRH74lzgdykykwXkOOxQnOzUFjfSG3eVpHui+HRrfKVY4RdurnRVVs0lScbD9aERj+fyaCGUnqt3/eJafhTtshFLbr9BSmYQh55+3zwJ609zbToc1BwqVWAjrKD8HMM0+t1Ke34SR78B+372cInCTSorC7mXgE4Ih6IMF6plqXGFLrr0l+dbHwgqsGwsw6f7ihrk/spwCiQZxxIaSYLt73lgYh8lGiA1lGLuV3F2Rh+fAiS1l
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: mediamanager-db
      namespace: mediamanager
    type: kubernetes.io/basic-auth

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: mediamanager-minio-store
  namespace: mediamanager
spec:
  encryptedData:
    accessKeyId: AgA+bHfEsCXhfx3e1mITnPAN6iHX2NUWWCinX2MrRoIzD2NkW3CMt10yE/hm35B259kneFRu0YdEG7PsRXm72P710wp1o2Lg6b49JXsuxNKr3dnNZtgWevyA7dMjt4LAhKB1VFVuvFuuneEmKIkIE6zOMH2W0wAOe7Ma1ve21LpEPA0+Ocjz9YAO16EoCZytUHPl9t96iqGomRL4DLsbMZtgxZmzk6n4BZ4cE1NDqvGPwg2vxbvSzYzSo2iu7iAfYPuNU0+9aaHOLkeixkZZVpu25RQ5nGSh6GHPkjvfqdVGqrX01ieW45RLvkPDEtk/oaC39CzjLuMUvqoSrE2nKENIxw/t4mYvrcL16VpxtDB7VNPV6mO5JkUx1r5cZ/MpzrDWicNXE/dvnp9DNNKEjkBwa5BFU335xDbNvwktqylfCrYbfLCNWif2pNJ6SCpUKvUMXzS/8bMem6HflaaQjp53YCdGOa0Lt2UN/Xlxwg9BlUYhrrLz309cL0xvZ7fDorijBTAXR0akuDE1ituiJ2MhZdbe4spaRJH/hh6za1LI0ZREHpaaXqM4T02j7D/54LclaM1y2iZkK0kBAl3P7ICSycLfSPDnl4gXF7Dfm6haOkqZuelCzrOi7bJH/tKALPoxxTQCYiC7guouji9/xB+odLwZ1Hnp3ixoBWhkiPpQkEGqyFjegamlsleUIx+RLfmOOJWXW0yber7ASC876Bc=
    secretAccessKey: AgA03HoGoulK96xSYwu1YBLwU9sf8uuwVoSOsfqKcIqASQSPzaQAvPwRZT7QPkebTadwlhFxGXrZklPJrxCuOoVtW+67NynCZCbElav1WElQSeO+L8dBiM9aZjW+w9XyoEnQjGbumDFAnBDAhHVgpOof7craws3bzdfvON+hrM46Gv+2mtebltYDECS4YTmM/P5Sgd6X/mkAwqxx3Mjg55WJky9y1yJAaZsxBhVzpeHqCl1c7ZV8FCAiOEeKFW+lPaMfCZsne9a1tHaaUa5UjfErMzUvbQBzxyp9L4cL9RcZQQIxQ1wPjwQdvtQLFTgkjFUgH1j7YWX+BGwDcqfab7ywbFopLfV9MfdyZbTu4eSXAJEWOxqEXNgUeBBuU0Pt6JiqfIx9dZMtaWN793OufCnpz4Xr+OajGsLfUxaY1tuD9DtYKozirPRYuXXD1ncfEPyrrKoUh5lGt0+mahshP8SydjAfNJ28LrMb/hq5IGazeCLOuui6Cm4KCWKOT9s3o7Jxize8IrA9GeSCXyJlrNHNgq1sIqSb0fNyroWBU0xR9iB1qrqiQwwC2PcjfndwqIvhQdefxMhFUz4fyEPEFsPIIdJYCGdJxzoDRoMZnAAT4Kk63RQS+wfQuKM1n6KAmukqrjm8iEu8E746qzhKLQfoQaxpsEQqXEk1vuxUPKIBrZ8gaqIICQvo0pS9JM73BB7H0OL2b1DQJ2il7MTNzXCQY3HRqmToPrVDqfIBPhg=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: mediamanager-minio-store
      namespace: mediamanager
    type: Opaque
