---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mediamanager-config
  namespace: mediamanager
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mediamanager-images
  namespace: mediamanager
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
