apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: controllers
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  sourceRepos:
    - 'https://github.com/schaermu/homelab-k8s'
    - 'https://cloudnative-pg.github.io/charts'
    - 'oci://ghcr.io/lexfrei/cloudflare-tunnel-gateway-controller/chart'
    - 'https://victoriametrics.github.io/helm-charts/'
  destinations:
    - namespace: 'argocd'
      server: '*'
    - namespace: 'cert-manager'
      server: '*'
    - namespace: 'node-feature-discovery'
      server: '*'
    - namespace: 'intel-device-plugins'
      server: '*'
    - namespace: 'kube-system'
      server: '*'
    - namespace: 'cloudflare-tunnel-system'
      server: '*'
    - namespace: 'longhorn-system'
      server: '*'
    - namespace: 'cnpg-system'
      server: '*'
    - namespace: 'vm-system'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
