apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: network
  namespace: argocd
  labels:
    lab.schaermu: network
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  generators:
    - git:
        repoURL: https://github.com/schaermu/homelab-k8s
        revision: HEAD
        directories:
          - path: k8s/infra/network/*
  template:
    metadata:
      name: '{{ path.basename }}'
      labels:
        lab.schaermu: network
    spec:
      project: network
      source:
        plugin:
          name: kustomize-build-with-helm
        repoURL: https://github.com/schaermu/homelab-k8s
        targetRevision: HEAD
        path: '{{ path }}'
      destination:
        name: in-cluster
        namespace: argocd
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - ApplyOutOfSyncOnly=true
          - ServerSideApply=true
