apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  schaermu.lab/project: infrastructure
  schaermu.lab/app-group: network
  app.kubernetes.io/managed-by: argocd

resources:
  - project.yaml
  - application-set.yaml
  - tunnel-device-plugin.yaml
