apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: network
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  sourceRepos:
    - 'https://github.com/schaermu/homelab-k8s'
    - 'https://prometheus-community.github.io/helm-charts'
    - 'https://argoproj.github.io/argo-helm'
  destinations:
    - namespace: 'argocd'
      server: '*'
    - namespace: 'cilium-secrets'
      server: '*'
    - namespace: 'cert-manager'
      server: '*'
    - namespace: 'gateway'
      server: '*'
    - namespace: 'kube-system'
      server: '*'
    - namespace: 'external-dns'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
