---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jellyfin
  namespace: argocd
spec:
  project: streaming
  source:
    # chart: jellyfin
    path: charts/jellyfin/
    repoURL: https://github.com/jellyfin/jellyfin-helm.git
    targetRevision: master-vnext # use latest chart version until 3.0.0 drops (HTTPRoute support)
    helm:
      releaseName: jellyfin
      valuesObject:
        httpRoute:
          enabled: true
          parentRefs:
            - name: internal
              namespace: gateway
              sectionName: https
          hostnames:
            - jellyfin.lab.schaermu.ch
          rules:
            - matches:
                - path:
                    type: PathPrefix
                    value: /
        nodeSelector:
          intel.feature.node.kubernetes.io/gpu: "true"
        resources:
          requests:
              gpu.intel.com/i915: 1
          limits:
              gpu.intel.com/i915: 1
        volumes:
          - name: series
            nfs:
              path: /mnt/MAIN_POOL/media/video/Serien
              server: 192.168.1.244
          - name: movies
            nfs:
              path: /mnt/MAIN_POOL/media/video/Movies
              server: 192.168.1.244
        volumeMounts:
          - mountPath: /series
            name: series
            readOnly: true
          - mountPath: /movies
            name: movies
            readOnly: true
  destination:
    name: in-cluster
    namespace: jellyfin
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
