---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jellyfin
  namespace: argocd
spec:
  project: streaming
  source:
    chart: jellyfin
    repoURL: https://jellyfin.github.io/jellyfin-helm
    targetRevision: 2.7.0
    helm:
      releaseName: jellyfin
      values:
        # expose using gateway api
        httpRoute:
          enabled: true
          annotations: {}
          parentRefs:
            - name: internal
              namespace: gateway
          hostnames:
            - jellyfin.lab.schaermu.ch
          rules:
            - matches:
                - path:
                    type: PathPrefix
                    value: /

        # schedule jellyfin on gpu nodes for hw acceleration
        nodeSelector:
          intel.feature.node.kubernetes.io/gpu: "true"

        # enable hw acceleration
        securityContext:
          capabilities:
            add:
              - "SYS_ADMIN"
            drop:
              - "ALL"
          privileged: false

        # mount media nfs volumes and hostPath for hw acceleration
        volumes:
          - name: series
            nfs:
              path: /mnt/MAIN_POOL/media/video/Serien
              server: 192.168.1.244
          - name: movies
            nfs:
              path: /mnt/MAIN_POOL/media/video/Movies
              server: 192.168.1.244
          - name: hwa
            hostPath:
              path: /host/dev/dri
        volumeMounts:
          - mountPath: /series
            name: series
            readOnly: true
          - mountPath: /movies
            name: movies
            readOnly: true
          - name: hwa
            mountPath: /host/dev/dri
  destination:
    name: in-cluster
    namespace: jellyfin
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
