apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: streaming
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  sourceRepos:
    - 'https://github.com/schaermu/homelab-k8s'
    - 'https://jellyfin.github.io/jellyfin-helm'
    - 'https://github.com/jellyfin/jellyfin-helm.git'
  destinations:
    - namespace: 'argocd'
      server: '*'
    - namespace: 'jellyfin'
      server: '*'
    - namespace: 'prowlarr'
      server: '*'
    - namespace: 'download'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
