---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: cloudflare-dns-credentials
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCBU+Om/GWAW/VhVZ4vTWc6xVPecy6YXKeDew+hPC7ZlaIRWzkNfOxI22wisdLJuEf96P6awf4yYXjQXM6+4GBNusr1lwvu67162jPkpAjNQD18/sxc32OyHYlgBAwQW1MYoscHhHu0LiPT0nibE2NFthj/zx4g5hV7or6BXKegFxiqso7bHMGYhdHEup5a0jy4p/iU28CdZKOsWzhTMR3UIKUrEK7HT5Dyf3jYH9euQu3ab6GLt35bc609h2CrIAa9TewNmqzgy9W8UwfcN0XocsrzFk+7moYxTbObKz0QRk8MRWzSk/XjSJYMj+IyvZRriS/Yy5ksNHQrbSWRNLmEUCckhLSUReqn4muA0vXAwn92qY8nDAh88l5+Pv8tAk23s1GUcHravraojWSVtHtPvsDZ8XMaaXrkpG1bpsVEFQIiIB5R1QeFGSnBtW3MR4X+LYF6bF97BG20hkQCdI4MIiG9Mq2vBMVgqM7A1ycj5CKeY2/zGYEF5gfD0j8v/SIS1IGpm0eJxhGCv4vIl7Ali2xlK9GppqFj7dqMzx53DZlsqKcNU2nHKvX2C7VNQB2TuhW9DymYGGycVQZajKhflnpKAtMgmOof0qPSajtcr/QeZa+OoUuzPh8ltG2GaSIW85qSK5tsgyZJQ2RC8sNTfegHf3FTsQ23Qao3FhOMjg8JAwMz0EUbiVPi3d/IcARNXEm2qMcNqKepNOT4o9ez6noZCb4/ymd5sICHiuuWgZalLBPFSUmA
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: cloudflare-dns-credentials
      namespace: cert-manager
    type: Opaque
