---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vm-operator
  namespace: argocd
spec:
  project: controllers
  source:
    chart: victoria-metrics-k8s-stack
    repoURL: https://victoriametrics.github.io/helm-charts/
    targetRevision: 0.67.0
    helm:
      releaseName: vmks
      valuesObject:
        argocdReleaseOverride: "vmks"
        victoria-metrics-operator:
          annotations:
            argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
          crds:
            enabled: true
            plain: false
        vmsingle:
          enabled: false
        vmcluster:
          enabled: true
          spec:
            retentionPeriod: "1"
            replicationFactor: 2
            vmstorage:
              extraArgs:
                dedup.minScrapeInterval: 10s
              storage:
                volumeClaimTemplate:
                  spec:
                    resources:
                      requests:
                        storage: 10Gi
            vmselect:
              extraArgs:
                dedup.minScrapeInterval: 10s
        alertmanager:
          enabled: true
          spec:
            replicaCount: 1
            port: "9093"
            selectAllByDefault: true
            image:
              tag: v0.30.0
            externalURL: "https://alertmanager.lab.schaermu.ch"
            routePrefix: /
            disableNamespaceMatcher: true
          useManagedConfig: true
          config:
            route:
              receiver: "discord" # this becomes the default
              group_by: ["alertgroup", "job"]
              group_wait: 30s
              group_interval: 5m
              repeat_interval: 12h
              routes:
                - matchers:
                    - severity =~ "info|warning|critical"
                  receiver: discord
                  continue: false
                - continue: true
                  receiver: blackhole
            receivers:
              - name: discord
                discord_configs:
                - webhook_url: https://discordapp.com/api/webhooks/1459589867729195248/TTeNj3Y6thH9onuxE_QfavGtzU6Ku5QR0xAKyLfojwVOVtx-S8VGVseE5p4lZezS9mqJ
              - name: blackhole
          monzoTemplate:
            enabled: false
          route:
            enabled: true
            parentRefs:
            - name: internal
              namespace: gateway
            hostnames:
            - alertmanager.lab.schaermu.ch
        vmalert:
          enabled: true
          remoteWriteVMAgent: false
          spec:
            port: "8080"
            selectAllByDefault: true
            evaluationInterval: 15s
            extraArgs:
              http.pathPrefix: "/"
          ingress:
            enabled: false
        vmauth:
          enabled: false
        vmagent:
          spec:
            scrapeInterval: 10s
            replicaCount: 2
          route:
            enabled: true
            parentRefs:
            - name: internal
              namespace: gateway
            hostnames:
            - metrics.lab.schaermu.ch
        grafana:
          enabled: true
          plugins:
          - https://github.com/VictoriaMetrics/victorialogs-datasource/releases/download/v0.23.2/victoriametrics-logs-datasource-v0.23.2.zip;victoriametrics-logs-datasource
          grafana.ini:
            server:
              root_url: https://vizmon.schaermu.ch
            auth:
              oauth_allow_insecure_email_lookup: true
              #disable_login_form: true # comment out for initial deployment
          admin:
            existingSecret: grafana-admin-password
          deploymentStrategy:
            type: Recreate # to avoid issues with persistent volume claims
          persistence:
            type: pvc
            enabled: true
            storageClassName: longhorn
            size: 500Mi
          sidecar:
            datasources:
              enabled: true
              initDatasources: true
              label: grafana_datasource
            dashboards:
              provider:
                name: default
                orgid: 1
              folder: /var/lib/grafana/dashboards
              defaultFolderName: default
              enabled: true
              multicluster: false
              searchNamespace: "ALL"
          forceDeployDatasource: false
          vmScrape:
            enabled: true
            spec:
              selector:
                matchLabels:
                  app.kubernetes.io/name: '{{ include "grafana.name" .Subcharts.grafana }}'
              endpoints:
                - port: '{{ .Values.grafana.service.portName }}'
        prometheus-node-exporter:
          enabled: true
        kube-state-metrics:
          enabled: true
          replicas: 1
        kubeApiServer:
          enabled: true
        kubeControllerManager:
          enabled: true
          service:
            enabled: true
          vmScrape:
            spec:
              jobLabel: jobLabel
              namespaceSelector:
                matchNames:
                  - kube-system
              endpoints:
                - port: http-metrics
                  scheme: https
                  tlsConfig:
                    insecureSkipVerify: true
                    caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
                  bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
        kubeDns:
          enabled: false
          service:
            enabled: false
        coreDns:
          enabled: true
          service:
            enabled: true
        kubeEtcd:
          enabled: true
          service:
            enabled: true
            port: 2379
            targetPort: 2379
            selector:
              component: kube-controller-manager
          vmScrape:
            spec:
              jobLabel: jobLabel
              namespaceSelector:
                matchNames: [kube-system]
              endpoints:
                - port: http-metrics
                  scheme: https
                  tlsConfig:
                    ca:
                      secret:
                        name: etcd-secrets
                        key: ca.crt
                    cert:
                      secret:
                        name: etcd-secrets
                        key: server.crt
                    keySecret:
                      name: etcd-secrets
                      key: server.key
        defaultDatasources:
          extra:
          - name: VictoriaLogs
            type: victoriametrics-logs-datasource
            url: http://victoria-logs-single-server.victoria-logs.svc.cluster.local:9428
            isDefault: false
        kubeScheduler:
          enabled: true
          service:
            enabled: true
          vmScrape:
            spec:
              jobLabel: jobLabel
              namespaceSelector:
                matchNames: [kube-system]
              endpoints:
                - port: http-metrics
                  scheme: https
                  tlsConfig:
                    insecureSkipVerify: true
                    caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
                  bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
        kubeProxy:
          enabled: false
          service:
            enabled: false
        prometheus-operator-crds:
          enabled: false
  destination:
    name: in-cluster
    namespace: vm-system
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - ServerSideApply=true
    # https://argo-cd.readthedocs.io/en/stable/user-guide/sync-options/#respect-ignore-difference-configs
    # argocd must also ignore difference during apply stage
    # otherwise it ll silently override changes and cause a problem
    - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: ""
      kind: Secret
      name: vmks-victoria-metrics-operator-validation
      namespace: vm-system
      jsonPointers:
        - /data
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      name: vmks-victoria-metrics-operator-admission
      jqPathExpressions:
      - '.webhooks[]?.clientConfig.caBundle'
