apiVersion: batch/v1
kind: Job
metadata:
  name: etcd-secret-writer
  namespace: vm-system
  annotations:
    argocd.argoproj.io/sync-wave: "-1" # happen first
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "etcd-secret-writer"
    spec:
      automountServiceAccountToken: true
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: Exists
      tolerations:
      - key: node-role.kubernetes.io/controlplane
        operator: Exists
      containers:
      - image: ghcr.io/schaermu/kubectl:v1.35.0
        command:
          - "/bin/sh"
        args:
          - "-c"
          - >-
            kubectl config set-credentials sa-user --token=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token) &&
            kubectl config set-context sa-context --user=sa-user &&
            kubectl create secret generic etcd-secrets --save-config
            --dry-run=client --from-file=/system/secrets/etcd/ca.crt
            --from-file=/system/secrets/etcd/server.crt
            --from-file=/system/secrets/etcd/server.key
            -o yaml | kubectl apply -f -
        imagePullPolicy: Always
        name: kubectl
        volumeMounts:
        - mountPath: /system/secrets/etcd
          name: k8setcdcert
        - mountPath: /home/kubeuser
          name: home
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 60 # this is what etcd runs as; without this we can't access the etcd certs in the volume
                        # that's also what the Dockerfile specifies as the UID
          seLinuxOptions: {}
          seccompProfile:
            type: RuntimeDefault
      imagePullSecrets:
      - name: secret-name # if you need it like I do
      volumes:
      - name: home
        emptyDir: {}
      - hostPath:
          path: /system/secrets/etcd
        name: k8setcdcert
      restartPolicy: Never
      serviceAccount: secrets-writer
      serviceAccountName: secrets-writer
  backoffLimit: 3
