---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ns.yaml

helmCharts:
  - name: victoria-metrics-k8s-stack
    repo: https://victoriametrics.github.io/helm-charts/
    version: 0.67.0
    releaseName: vm-operator
    namespace: vm-system
    valuesFile: values.yaml
