---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: grafana-admin-password
  namespace: vm-system
spec:
  encryptedData:
    admin-password: AgBx2g33471m9z0xAR1d7y4Y3LKx9guQ1TCybRgOh51dg9Mabn0IXdS2O1zTPWPx+CLK0zg+qevzbLsgQgyUrmZiqpiD4kPVX8QqFUwB9vizAiSVCu8ad3KN3m9TxgdDu49iOBUurSJc4AGDOnqZ38nvXRS9chCFW37GzyGzMq//UqnuM+3C9otacUCcoP4CgwFu2sU0dYZglZ9YqzQTcbt0l3u+YLu4njLHTlZKroYX+u1rcc0/bVozg7ANKfYeUsUZWEE5y6MCiMFF5wcWes8FDLh4zH2O9bVm5ibix6bGhpv+MKe/bHvNl3cvcCWRVGzybzWBhyGgu/1zwgMdw5bzFArz7gjc8yU39RNzqvxFPDMHuRG8hFP76pKPttKi20M4YVWNfpgcE+5m2hfZrAu5QnPqrRMYZP3B9No7zaSm7YyIXClVfifvyaAuIE6h+asjoBMgmzcPCDOFXC7atajNAR5MRxLffltgEczMrhCAkOH2r04y81Y6EUr+35QyrS5HHdwqmk0VdPzTHXwcBWxo01FBJ3DAJgsPkHis5007XC/175VVp5oVelpnXzfEcfc2gVlCy+kwHdKJQEI0nPmvNOk0jw4VRVtcqX+1bbw/9jXu7rsacNIHPhv6bjTrvhosKST2hyn6q8qbghg9w0L6WKXniTrYofpHsR2kcLbGQjCCKOldfztJiR5Wna6d5I6TU55qGBw0ZQsK/suIeck=
    admin-user: AgA+0MMs6ACS4Muyfy6ykJr1p9ozecLM9uD1ARO8M51Ih8qDuk45DUYILKFKXjgCbLd68aqt3/y+r72xf95HQGv6ssu02OBB29HKfFkknSZQN5Y20G6PTQh7ts9EslUsPVbiAW+61UYJ7tB2axDU5oPUQxHkAhW9oMdqIjlbOVdQYk8iLXFQmaxHLMokcVjDvTnib767hKkj7+g3koVzNRx+jMmPgZBYNS5G3lX1vT7BTUR98A/+OwP5Dwfx/IFOfftyF2yqYyc3tuxvlavigmA3OvBHzBp/fMRP109J+KJeIIKPO9lSh6OCrRGrXwlQArrFPnGhpd96fcvwhiPqe1uPczNVkvARSN3gZPx3LXTGR+dPmPffatkzM5ztXDffyPWjU2IlfP+vMr7hKxiDnLkmpHSLZKXYkbyJkRNmP7ynThf7GjyxPv6X0ZAcZBmasbztkRogRKwL4xVwJ/w4PBz30N93BJ839wCew1ZHQUoXTbxBeXdvoRa92x5HMIxU4X6uNVEnvs/LMtd8O2+RBHBBBwTm227G8qKK26pludag8QkYWy73fu0tgLVRWeEpx8IZ9ODZgnCWX8RqeCC/FEpmDZRDCBR7A3Tp6d2q3I2JIBP+DnHCtVqFMwU9BivtenL7grfwhuduHsqdy3YQq0LuqDMDnZvhN+1jEbqWglal6lS2RLDRU3KdvvgpJzMeEe+OszshBA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: grafana-admin-password
      namespace: vm-system
    type: Opaque

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: alertmanager-discord-secret
  namespace: vm-system
spec:
  encryptedData:
    ALERT_WEBHOOK_URL: AgAIfqaEcXcvI9i4WPc8FjQ0HcSOiHdaTHtD6tTStj1O/XpL26URkMyYVJGITn4xmY+kYSw8F8MsJTyWoI2xgHs2MZ2Yww9XeI+Q6rnrp4wSK2riNKH/ls3Ub2oeqBU/s8bnAs6OtKPIEjly9YdKILQYqadQ/umjNPpTU58sx8XJeshkyinsW+CtZaQ4VbnlLqzuaHc+TlfLOjAduOjlBQHZIktp05dO2c0dEIEdnEuBBtFJWrSFRyUsRK5kOQObQEfAvfuF4wOTYimGKfmAdaijH4WbYwx6stSCyKB8t+UYkXYsg/CdDIVBvKpAo08hK3hg2SIlusnsqe7rxgAVkI+fShDL9H3qfrgOpHGdC0UugkrNvN3FosU33Uw42ByR8DD4RyeGTMHMgwdgCS2tnzGT15+dqgjDO4h4l03HfHHd+7PgtFcNy5BjUhaXEBGrdsRIH/4V1xZCoaSJ5lUNqicGsLQp3K4eRbZS7MbpmjQN0ZN3kWVS7AnMwE8KL8R6VOM9TjGZTSWYaCDx2nHm0qlO9lGV03VJ9LkA8UESbhXhuRM/s3pP/SIVM7FBBe/siB4kf80ranSSKFdR5C1ErO5PLq2e8jsZnff1aX9vnKkf/2jNaau1lcnhglTJVxG5TExxrNlcNXQEDUVc1RAtern43nL9PjyviG7+xhFAlYbqEc/xFPdMHcT0ft1s1ZNFgH7yMjGkSlTnCBZyLhPzZfjaIFQhy/mSyyHUhT3KE+/WQTnmGwh2WwqvUuNuRoJH/IP4Yu2Zq1KW9M66GXCthyNpBgXmQrcKZzYsZ4QoOtWrXlmpS2UBlwqQcY8icFzedlRDVUpIwL567ZpEBUmraW8OTq8RKsaYozdT3vpy
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: alertmanager-discord-secret
      namespace: vm-system
    type: Opaque
