argocdReleaseOverride: "vmks"

victoria-metrics-operator:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  crds:
    enabled: true
    plain: false

vmsingle:
  enabled: false

vmcluster:
  enabled: true
  spec:
    retentionPeriod: "1"
    replicationFactor: 2
    vmstorage:
      extraArgs:
        dedup.minScrapeInterval: 10s
      storage:
        volumeClaimTemplate:
          spec:
            resources:
              requests:
                storage: 10Gi
    vmselect:
      extraArgs:
        dedup.minScrapeInterval: 10s

alertmanager:
  enabled: false
vmalert:
  enabled: false
vmauth:
  enabled: false
vmagent:
  spec:
    scrapeInterval: 10s
    replicaCount: 2
  route:
    enabled: true
    parentRefs:
    - name: internal
      namespace: gateway
    hostnames:
    - vmagent.lab.schaermu.ch

grafana:
  enabled: false

prometheus-node-exporter:
  enabled: true

kube-state-metrics:
  enabled: true
  replicas: 1

kubeApiServer:
  enabled: true

kubeControllerManager:
  enabled: true
  service:
    enabled: true
  vmScrape:
    spec:
      jobLabel: jobLabel
      namespaceSelector:
        matchNames:
          - kube-system
      endpoints:
        - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
          port: http-metrics
          scheme: https
          tlsConfig:
            caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
            insecureSkipVerify: true

kubeDns:
  enabled: false
  service:
    enabled: false

coreDns:
  enabled: true
  service:
    enabled: true

kubeEtcd:
  enabled: false
  service:
    enabled: false

kubeScheduler:
  enabled: true
  service:
    enabled: true
  vmScrape:
    spec:
      jobLabel: jobLabel
      namespaceSelector:
        matchNames: [kube-system]
      endpoints:
        - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
          port: http-metrics
          scheme: https
          tlsConfig:
            caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
            insecureSkipVerify: true

kubeProxy:
  enabled: false
  service:
    enabled: false

prometheus-operator-crds:
  enabled: false
