---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-data
  namespace: jellyfin
spec:
  storageClassName: ""
  selector:
    matchLabels:
      type: nfs-shared-storage
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 20T

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-data-pv
  labels:
    type: nfs-shared-storage
spec:
  capacity:
    storage: 20T
  persistentVolumeReclaimPolicy: Retain
  accessModes:
  - ReadWriteMany
  nfs:
    server: 192.168.1.244
    path: /mnt/MAIN_POOL/data
