---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-media-pv
spec:
  storageClassName: nfs
  capacity:
    storage: 20Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/MAIN_POOL/media
    server: 192.168.1.244
    readOnly: false

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-media-nfs-pvc
  namespace: jellyfin
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Ti
