---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflare-tunnel-gateway-controller
  namespace: argocd
spec:
  project: controllers
  source:
    path: .
    repoURL: oci://ghcr.io/lexfrei/cloudflare-tunnel-gateway-controller/chart
    targetRevision: 0.9.7
    helm:
      valueFiles:
      - k8s/infra/controllers/cloudflare-tunnel-gateway/values.yaml

  destination:
    name: in-cluster
    namespace: cloudflare-tunnel-system
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - ServerSideApply=true
