---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ns.yaml
  - secrets.yaml

helmCharts:
  - name: cloudflare-tunnel-gateway-controller
    repo: oci://ghcr.io/lexfrei/cloudflare-tunnel-gateway-controller/chart
    version: 0.9.7
    namespace: cloudflare-tunnel-system
    releaseName: cloudflare-tunnel-gateway-controller
    valuesFile: values.yaml
