---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: cloudflare-tunnel-token
  namespace: cloudflare-tunnel-system
spec:
  encryptedData:
    tunnel-token: AgA95/i1qzMkxpKiAZACocEBHbRW0MVvS1VJqoatA/CG275dA/X/KSIG1fQmRkbttDXJIErF7lUD1X4Jrle0NjYbIBdrGiMmzVQBbZBlrySv5uPbaiaxqkYgrmIz+xmzROePXKYKFS4YyDn+D5wLvsjQZWgZrmI4wVvXfN5SSgTZVbjOKUmW+8OQ1zGemBhrKglcagoQ4Z+tujDdbiFNwj+RatnmtCW3yEQS58nMq7Nv+g+wnepPY1CI26J017cZ2Xq779V5+VSR2Kcxgca5yx4qQ8/zY8iMK2+VgWZHUbCvOjdXIrJm++Y2pdCS7YryPf0hayuuTTdxgSfNyD5ur+d63GaADm4pytXhIgM9vQI1uj4UqSvMyIZWtl1tv/HpaFxYrKLsYG1GsmA41WaLYiroNXOOu698wiaz+d9TgQ6KSZF9OlnGZ36ZDeG8a4i8PcTvmkhSElzTujCfT1WBbsXb5Ppjdc8bqH+uDMVIWa9vFfm247iebth8xafxmTkhBFYLjY1f5vb/ipe6f7SaYOkTCP8nmZ03vxK09EBaTTz38pnPJpew1yDRCtOKyi0ZOCyILfZjVJdq/dm/0jSTid9zGHN/XQPaqJYOpom9xeAUm4jdHdFBDmvsQ0k9ThV2ERgzF1L4LoiAJUySckLqphrZ22ckpiiTStnf89jpxuFucrJuNqg8UIL4jjbRKt0uZH4yE22i6pHktSPAMO0j35c+pEtV2PZmmgk3TcUAn8t77RiX7ktIAiVBnr5TvLXUrWkpN878GuSfocd/i/CJDl/6+A2nBu326oN6S97FK3o7+I+2cLg7wTURAv4FlgrIQr+Z7HcZPoEvc4EZlJ2NK9D5HT8llnmIJRsyfnIH4mPbSpS6QZ2rKoRTiWHcjODZHAfjqTcQd4G0YoYzI25EK/3j0VhkVq3lHjyDPiauEhsHN1JklrSwkAwc
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: cloudflare-tunnel-token
      namespace: cloudflare-tunnel-system
    type: Opaque

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: cloudflare-tunnel-credentials
  namespace: cloudflare-tunnel-system
spec:
  encryptedData:
    api-token: AgAIxJvXodOAOYKaTdvNkMx22zofiBzEoHruRnA8uoZIOxbxruNvfDUQx47BAOyzx/KB7CGhY+qqwP4dZaj90Ggk/NitvYshD8VNjKki64zO9aTGuZHa5OQO5Rt+ZUXNPj5jWidEJoT04EMi3NstoOPAYPKd5kQLu57JU0cE5yql/T/fe5+GdnkQ3EUvt2byZQ/8NHJ/57xLB+qFfUgaE+QQpO4g2Azs3a97khmUUGjsNr7rtP7n2R87Z1A9yZY1YY+Gy8oRhLE4gdD0UsN2Ahnj18Tg7IGlRikQdsJiYLUz3qvPqiOd87AZzLJXQXgJznOUva6Qh/ozfGr9Pckv4PCw6qvgGueHd8WHtSbFVgKK8FRAYGPATHVYFisf6ldRwx4RSsksvcZqL0ij5tfbde1aleVvR0JLM+QxMAFtUb8YPpTlGSzeS7YpWygcqJA73ejx1M7ASm9zRsSA6OABcbuJEOC4Oo7Aht12pQWzhbqdJjYoJD+tj1pLFjXur9Y3DDutmStHgCDCtimiuKxkr6l0G1rrx7S+MJidRchhOYDu3+3fHVF1hhSkTwGxMMD3P40/Hynv2CQSrd4E5S9hYmjk4QjId6EHI7zdNShuzdWWGgshQrc7/wAAzpLqpLs/EB0D0tOh85wHS+PDdtdJTLLlD0wYSdh9UQ7oPNFGfOewwWqAvA8bB/UNv+tgU1FgED5wA7RwEZgyZR+KColQA4iibmr1OzTQQrr0NW4RbbiNkWC7UEqDKz6O
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: cloudflare-tunnel-credentials
      namespace: cloudflare-tunnel-system
    type: Opaque
