---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-tunnel-token
  namespace: cloudflare-tunnel-system
spec:
  encryptedData:
    tunnel-token: AgApTaishEId12RDRZnaYayNZjtKWTEBh0nU696xJuZp6g5QkE6XcDQxyMZcAqyJhyC7BzQyChZpdQRFzfh+TJUcgP+NM6FTcOU1if2gnAIMgIuOqXxH1LBMmocyU4P2CThoLL4a/YcOM6XMUhnqq7WKf8LWCQ+Khi7R+kzPmOp14Zp9I7LS+3wTTgT+Mtup7oJW1iXFniRBw/C+9/vFGUU4e7xUua0/MT23m1wl3wHR5hG/08R1CzBpUE60SKGh2KFH6ORaBzXt5QWJFOiE/JQ5ZvVjQiAZHDJUOaZ+z1FhhwKHD7le5bzccF75cKDyFgyII74ZuL7hBXYfT62n6lhXLhYE+gsO1KFmIQh64u0jwhIJpnc4oR4H757IVKJ3EunGicE+nyRIL2EdDZf6FWjJvNt8WsYYzXNNSlzpe0/xqnESYceRUiW1ZtKT2XEbb4ZVU1bmjKd/eqvQ96kl8lDV/SrgXs5yOCfpI+icEyAnyCvbkimZkoPWEBr3d3QjtVzqvdM13XciDwWhoZ8nccEiuRvzYgjIxVd4c4YCXQxpZGiXQzAKmMpoKDwy6BXrN8J1yONFbTB5LZS6YI7Ey00v32FIsEOWoEwSbQA8pFLDZMO4bOY14HGPRD5Ena1rVnoFBRzfjFP/tD+hKPR0rZCaHYB4K/XVesv2E3iTHFqGkgdM+gsgdKPYBGqrBJ43eJX5xp9LM0WE0H7lDUFu2Z0QTmvvF2Qzlfwmni25F5g1nYg9XGZcNOJiVZgUweOt/aC0bBjqEpM50O4be2Bcm4gANkX9sdN2BeRkEgluFUBEv3DqX+ladm/hgUuIqssTXoGTHJmBTAHJRmkYMje+RsLpqw+BAMFaMjViKkV1Dw8YIiqBFlrAepcMVFkrZEnE8iuAG0set6I0mKZYFZcaCXPUK+rf6NOdYaKMEyoXaeWmRIKI20VAZ9VO
  template:
    metadata:
      name: cloudflare-tunnel-token
      namespace: cloudflare-tunnel-system
    type: Opaque

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-tunnel-credentials
  namespace: cloudflare-tunnel-system
spec:
  encryptedData:
    api-token: AgAkkpmlEuKdHnbZ5fHBuooF94AG0uJ8Ec8t36bTR+jut05Mc6+0mAuxpNdlsKtY+pv86ZPU2lxkQRNVS7XG2Ak/mrGOAgt6nI4m8Wdj6oLuuWKbaL1xHsZSzdfdFY5swCdXYpNOxXp+rPOmwoA3qHPUtgpdimw7YMlmSs9dAPUpFCiaBn4uJZWGg7M/MlcWMocS9tnOPeS+c7ZXfrn8yclZZ4GUhlBi/PO0i6FLkup9GckdZoMqMp+RhG9qlpYfy0R4gbpoQlANyQEadYFlJsUpz35jK9hUeSxVlAdtsvqoqrYFdGMtLXvgfRABqPe2vvr4fpyfXtk86BMexE2aFUmZaTyALPkZNWx6pj1aXsYcwJaR3x1g+gci/E/Pmgk3uGkugIb1r58fbXF0QuvHDH438+qPHZ8/IoB2XYdlYHrHk9T0m0/ohZfcxUDE57t0c//a1INbuJKSPUlQMXohuijWrM8JHDi5c2LEp3fmu96nXJb/YfMPtTfrvntHchHo9WIKdNXTS4/1MfdwNjLF3gmOfCXA3ChjUOD5nt4bnFvrjmfRz9hio8eIpyAGM6+E5GbCBg5+RTG9nUkbmZFBna/84uK0PeaRHl+Nl5Uy6bfMhQhf9Y71Uj6TqLncLRquQzAgL5LHpxJKRv/e0pfAB5yb7npNqWgremhXUVIVow1Y+IcneCDs7f0t8meuJp6wTEAUTovfRn9myQ7zB9rSkhx2qNQDIhuJ41nOqmHR+l1W4MvThi74y072
  template:
    metadata:
      name: cloudflare-tunnel-credentials
      namespace: cloudflare-tunnel-system
    type: Opaque
