---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: cloudflare-tunnel-token
  namespace: cloudflare-tunnel-system
spec:
  encryptedData:
    tunnel-token: AgA95/i1qzMkxpKiAZACocEBHbRW0MVvS1VJqoatA/CG275dA/X/KSIG1fQmRkbttDXJIErF7lUD1X4Jrle0NjYbIBdrGiMmzVQBbZBlrySv5uPbaiaxqkYgrmIz+xmzROePXKYKFS4YyDn+D5wLvsjQZWgZrmI4wVvXfN5SSgTZVbjOKUmW+8OQ1zGemBhrKglcagoQ4Z+tujDdbiFNwj+RatnmtCW3yEQS58nMq7Nv+g+wnepPY1CI26J017cZ2Xq779V5+VSR2Kcxgca5yx4qQ8/zY8iMK2+VgWZHUbCvOjdXIrJm++Y2pdCS7YryPf0hayuuTTdxgSfNyD5ur+d63GaADm4pytXhIgM9vQI1uj4UqSvMyIZWtl1tv/HpaFxYrKLsYG1GsmA41WaLYiroNXOOu698wiaz+d9TgQ6KSZF9OlnGZ36ZDeG8a4i8PcTvmkhSElzTujCfT1WBbsXb5Ppjdc8bqH+uDMVIWa9vFfm247iebth8xafxmTkhBFYLjY1f5vb/ipe6f7SaYOkTCP8nmZ03vxK09EBaTTz38pnPJpew1yDRCtOKyi0ZOCyILfZjVJdq/dm/0jSTid9zGHN/XQPaqJYOpom9xeAUm4jdHdFBDmvsQ0k9ThV2ERgzF1L4LoiAJUySckLqphrZ22ckpiiTStnf89jpxuFucrJuNqg8UIL4jjbRKt0uZH4yE22i6pHktSPAMO0j35c+pEtV2PZmmgk3TcUAn8t77RiX7ktIAiVBnr5TvLXUrWkpN878GuSfocd/i/CJDl/6+A2nBu326oN6S97FK3o7+I+2cLg7wTURAv4FlgrIQr+Z7HcZPoEvc4EZlJ2NK9D5HT8llnmIJRsyfnIH4mPbSpS6QZ2rKoRTiWHcjODZHAfjqTcQd4G0YoYzI25EK/3j0VhkVq3lHjyDPiauEhsHN1JklrSwkAwc
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: cloudflare-tunnel-token
      namespace: cloudflare-tunnel-system
    type: Opaque

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: cloudflare-tunnel-credentials
  namespace: cloudflare-tunnel-system
spec:
  encryptedData:
    api-token: AgAy0H1DjzorvKANa+1wf7ZlQtH/9GKZtHwXzyFI+NN5dSB6FbeFchPsWuht++FBOaPzZc9cncGgMohtHqVlpXXjhEwfjXBMi//X5U/2N7Mc3SFpjmKm1W/916fBBbRkbkVHmX32D+j9g7Rk4bmhVdVKV6LTZpFlHKeUEamCnV8SVGJb8TERDZ48inp6qnKEMdkL0sY5RcXTWv6mwLA9tR+4xcpzft3IkaznK54gDGoYR12HFNsFN6CKNyYmYdiRTn9DI53iMoFq0RK636MSam9WFx3iXoPiBq/LPBy53oA52fKRKDLLYpNHRBAh3lt4os8ESlBSL5sNhuM0A34NlWwRHYNFUgls55oWMfPU0+/ljmc2dqSGIovWQqm21g1fHI9kteWW58p4A3T0YgBxQoidzw7CHrYbxsjVTRuDVhPTEnMilz3rBGD/hvkjq5IiZJ77EqEOvJHgubCLBmOBG8IDTMeP3KTaa/Anxq/qvnXNFTpZVnRH3wCeIBlJk0FfU9uLsOkwXfVrb8upgpPzdw4IXr6EyKQzKAbK6U5SkHxtjCyuVx65daLnP1URHQ7Qo2t0G2NAhpAXs72kxP2fPyX6QOhXoQD460+905GZj2rjD+sKd1fMqM/chw29kGefMIwvM8xyQ9OAGaFm/6NBMnQrEg4YhIjQ3pou6rLuJZSPZd8pDg/EGqEcGYoJK+RhQbiAXul/84BQkKtt0TCLRyc54EsFy5S6FUAT74qRQXN/5zquk6VW0OVs
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: cloudflare-tunnel-credentials
      namespace: cloudflare-tunnel-system
    type: Opaque
