---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: qbittorrent-gluetun-config
  namespace: qbittorrent
spec:
  encryptedData:
    GSP_GTN_API_KEY: AgAkJJlTdcYY1lUYBmCcnaAPRrEIkh8rk0hKb2hLuXgE9h/G4VbG5lT/pG51AdjQkXdHs0snBuLt33T3Zk9THVMAtqkX24XWlZBd6fKxbNFi6cEYW3iaM6rd3HBwJJ3+ksXc4kSgBNOOLRzValfsrb7SjzZCpzXn3C6o7vcSYJtheW/pxJkpiIgRXIRDjxi84algyYruHVm98P0PwXjmJvaVLu2XJoluLk8WG9zhl+0KtIgIj0yKW9veMDDqZdWT9LWp4M4nsZlm+bjz6dst1mioXbAZdqvZIYWAV+tvrPVzqiNS1FvNTfaOaE5MD+n2rKS2Y0O1ncTyLEpaly9Gu3CYByNA8G7n5QL24Nwv/zuFKHbsWWeQzNeQVfIDgk5EFzjqfaNGsyqvkp3svQsvMoGU9zEuEQulJeWQDkG3/RQ7bG9Xpyp2i03IS6EqozYSHfepoJWWy/v7AslvUgt+tdEl6e0jTGvirouzK2VxznjS5U2UpzQG+lNmeaxOzAN0xLYBNKryG9bOVVOJ1cbymBEou5eNDcv6q4NYvF60pcebdyr8O+fcR5CkxReWbOTMFYKtUNDUddVCDixXtGwGFuuODcWlqTjCFIfNq3LuyxRihgPjBIdL3eGbGJ7ry2LlmmAocpICO/PvuaYi7migfh5Ys2M4hJUrPxn0AxSu6ZuKWDdYo19dYesg57Y/NkccreHmPST7n6m/8OD3/zJcVuV9y4E7PEDMolSO75s6R5Ai3T971x2CH/Hqhh4WPHMbxXFjsu3JHkUKLryQEHPvKfMuKvNqRw==
    GSP_QBT_PASSWORD: AgA1tQkQNVqcKX84z7vwAF1rdq+8prIR/z5WQoYujr2fYUkaXqukZFVBm+uwLqWQ0zSUSwd+QXASLT14Xl9Q17SGwBYiNAZ72A2DDKSXN3j6qxTVjXNrB3JLXKSixSlkilOOV0DSICGTJCAV3LDAKb8hP7L47RKM5rO2MJzjCsW8zhWMUZAH76JMoeUlK6pnmvg+gssgADVcZlQGmS2u0UX67xV32SKlvJ3VNwwNl+Sr0Z5LYjTdWDP5FTFO0hsm/o3P99tm5FYk1qDf7Er1oxzWv2hs/HkAZBdLwNCU6dgjZrVq7DavpaFlq7RHgoh0RYN/bz3Jr0MIpL3WWJxvfPSfFMSRXq3M3fhPs73GCipr6tc0gwLglLJtFtAYexlSplCT6RR0X16g//T7ouWTznhYLrpxTBEfmKKyHURouE1uxjwxkUGxViNIhfH3CekT9FT6iRhP8Z1stkCD+AcAEL4YcXfVwF8gyWDwYsut41qX8xSWjtdAOE0bt7yMAmdxL5cEa3XLQsjUn+H29qyGDHmZMxYV0P9PBJRzxSp3BI4f5YbbOIaZGM/zMaHzBb+Vbdqpu69iCoQWdXls1RY/F+lUiFQbbBpIhjNjC5YuGbfP1rY4kmOiYoVduTIJbXlC86M3RkG1f9m+YdYo6MATQAYONgKdLf+/Li2IQ/sm5Vs2MRcdCin62PzW/W0zdao9nazq2LnCxHPfWJG4m2C7
    WIREGUARD_PRIVATE_KEY: AgA6h7LSnb6Cb3vxzm7aaZjoDrlKyFFjxSaqB2GkcIkc7P4zqzwJ2x+5T2ei4ENNkrLanU7CHlYRp5y6+ejjzpMq0+QBfpGib9CDoSNlhStAnoWh+pXFzo5bD0f3A/+OaSQOcHWWkW8sLSVHLBgTBou0v2keoH+u5Nkec7x2+QD41G3db6sb1FV6OyDKPbWbtzhy+YTtUschkSxUi4oaF5tw5IYJ8/YSEZRtRnRMrm5NQc4FxDPyH+VI7GzNsLr0ydUk2H3WPyxTfDQxaHRs4zsHZEFv3AvbuB3BvZ30aU5hd400APA40DIGjpRFvjHiPtRvhp+q7y/+326Uh3+PFqdtTfhndbQ1uLGhTXGqpcff3y6Ua34oTUXXTh5LXSPp0Li51uZqonLCGzwKfa+C75Xf8A27ns3KbjWgr7TpdVWAN9nfPD+CevGwYyFMWC084ViIEi3mfCo3z6f05uK5cg/fZBBQIQWREOiqOi+SR9L5jDgu88gbERXFahBsPt4atSDfNHSjII6k4W07O7ene84LUjij0HXRaumf+p2U7HqfKAUJPuABs9uVZXZn+Ch0NuuiBYNtshlgY6N7K4xRjJcVhEDn6w9QttVRddjn7vhXda97yO66yQID2nRxpc9NT4drDpz4akI0Z3SyGFtR7fP/sVXmGITzoYCJqJMmtqh9F9YMtfJphlMdsOWfXpWzJYMVFfStZi0+ZJTjI4rVep4n163IvQhThNGv3BNckh2DzQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: qbittorrent-gluetun-config
      namespace: qbittorrent
    type: Opaque
    data:
      GSP_GTN_API_KEY: {{ .GSP_GTN_API_KEY }}
      GSP_QBT_PASSWORD: {{ .GSP_QBT_PASSWORD }}
      WIREGUARD_PRIVATE_KEY: {{ .WIREGUARD_PRIVATE_KEY }}
      gluetun.toml: |
        [[roles]]
        name = "t-anc/GSP-Qbittorent-Gluetun-sync-port-mod"
        routes = ["GET /v1/openvpn/portforwarded"]
        auth = "apikey"
        apikey = {{ toJson .GSP_GTN_API_KEY }}
